'---------------------------------------------------------------------------------------------------
' <generated>
'     This code was generated by Query Designer v7.2.28.1 at 2020/05/05 02:08:59 PM model release 27, Form Generator v1.0.37.52 - Query Generator v1.0.17.24
'     
'     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
' </generated>
'---------------------------------------------------------------------------------------------------
      
#Region "using"

Imports System.Data
Imports System.Globalization
Imports System.Net
Imports System.Runtime.Serialization
Imports System.Web.Script.Services
Imports System.Web.Services
Imports InMotionGIT.Common.Helpers
Imports InMotionGIT.Common.Proxy
Imports InMotionGIT.FrontOffice.Support

#End Region

Namespace dli.forms

    Public Class FASIReleaseLetterActions
        Inherits System.Web.UI.Page

#Region "Actions Methods"
  

        <WebMethod()>
        Public Shared Function ItemsTblDataLoad(BITACORAFORMFECHA2 As DateTime, BITACORAFORMFECHA3 As DateTime) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            Dim response As Object = New With {.FECHA = Date.MinValue, .QUIEN = String.Empty, .PAIS = String.Empty, .PROYECTO = String.Empty, .DESCRIPCION = String.Empty, .PAQUETE = String.Empty, .MOTIVO = String.Empty, .CATEGORIA = String.Empty, .TFSIDS = String.Empty, .FUENTE = String.Empty}
            Dim selectDataTableItem As DataTable
            Dim responseList As New List(Of Object)
            
            
            Try
                InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("*")

                With New DataManagerFactory("SELECT BITACORAFORM.FECHA, BITACORAFORM.HORAS, BITACORAFORM.QUIEN, BITACORAFORM.PAIS, BITACORAFORM.PROYECTO, BITACORAFORM.DESCRIPCION, BITACORAFORM.FORMID, BITACORAFORM.HORAINICIO, BITACORAFORM.HORAFIN, BITACORAFORM.PROGRESO, BITACORAFORM.ITOPNUMBER, BITACORAFORM.TFSNUMBER, BITACORAFORM.PROGRESO, BITACORAFORM.PAQUETE, BITACORAFORM.MOTIVO, BITACORAFORM.CATEGORIA, BITACORAFORM.VERSION, BITACORAFORM.VERIFICADO, BITACORAFORM.TFSIDS, BITACORAFORM.FUENTE FROM BITACORAFORM BITACORAFORM  WHERE BITACORAFORM.ESTADO = 'REGISTRADO' AND (BITACORAFORM.FECHA >= @:FECHA2 AND BITACORAFORM.FECHA <= @:FECHA3) AND BITACORAFORM.PAQUETE IS NOT NULL AND BITACORAFORM.PROGRESO = 100 ORDER BY BITACORAFORM.FECHA DESC, BITACORAFORM.PAQUETE DESC", "BITACORAFORM", "Linked.DLI")
                    .AddParameter("FECHA2", DbType.DateTime, 7, (BITACORAFORMFECHA2 = Date.MinValue), BITACORAFORMFECHA2)
                    .AddParameter("FECHA3", DbType.DateTime, 7, (BITACORAFORMFECHA3 = Date.MinValue), BITACORAFORMFECHA3)

                    .MaxNumberOfRecord = 2000
                    selectDataTableItem = .QueryExecuteToTable(True)
                End With
                With selectDataTableItem
                    If Not IsNothing(.Rows) AndAlso .Rows.Count > 0 Then
                        For Each itemData As DataRow In .Rows
                            response = New With {.FECHA = itemData.DateTimeValue("FECHA"), .QUIEN = itemData.StringValue("QUIEN"), .PAIS = itemData.StringValue("PAIS"), .PROYECTO = itemData.StringValue("PROYECTO"), .DESCRIPCION = itemData.StringValue("DESCRIPCION"), .PAQUETE = itemData.StringValue("PAQUETE"), .MOTIVO = itemData.StringValue("MOTIVO"), .CATEGORIA = itemData.StringValue("CATEGORIA"), .TFSIDS = itemData.StringValue("TFSIDS"), .FUENTE = itemData.StringValue("FUENTE")}
                            
                            responseList.Add(response)
                        Next

                        With resultData
                            .Count = responseList.Count
                            .Data = responseList
                        End With
                    End If
                End With
            
            If responseList.Count <> 0 Then          
		    
            End If
                
            Catch ex As Exception            
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "FASIReleaseLetter", "ItemsTblDataLoad", String.Empty)
            End Try
            
            Return resultData
        End Function


#End Region

#Region "Lookups Web Methods"


#End Region

#Region "Form Actions"


#End Region





#Region "Common Utilities"

        Private Shared Sub SetDefaultValuesFromQueryString(formData As EntryData)
            If HttpContext.Current.Request.QueryString("inicio").IsNotEmpty Then
                formData.inicio = HttpContext.Current.Request.QueryString("inicio")
            End If
            If HttpContext.Current.Request.QueryString("fin").IsNotEmpty Then
                formData.fin = HttpContext.Current.Request.QueryString("fin")
            End If

        End Sub	


#End Region

#Region "Form Contracts"

        <Serializable()>
        <DataContract()>
        Public Class EntryData

            <DataMember()> Public Property InstanceFormId As String
            <DataMember()> Public Property inicio As DateTime
            <DataMember()> Public Property fin As DateTime
            <DataMember()> Public Property RootItemsPAQUETE As System.String
            <DataMember()> Public Property RootItemsFUENTE As System.String
            <DataMember()> Public Property RootItemsFECHA As System.String
            <DataMember()> Public Property RootItemsTFSIDS As System.String
            <DataMember()> Public Property RootItemsQUIEN As System.String
            <DataMember()> Public Property RootItemsPAIS As System.String
            <DataMember()> Public Property RootItemsPROYECTO As System.String
            <DataMember()> Public Property RootItemsMOTIVO As System.String
            <DataMember()> Public Property RootItemsCATEGORIA As System.String
            <DataMember()> Public Property RootItemsDESCRIPCION As System.String
            <DataMember()> Public Property Items_Item As List(Of Items_ItemItem)

        End Class

        <Serializable()>
        <DataContract()>
        Public Class Items_ItemItem

            <DataMember()> Public Property PAQUETE As System.String
            <DataMember()> Public Property FUENTE As System.String
            <DataMember()> Public Property FECHA As System.String
            <DataMember()> Public Property TFSIDS As System.String
            <DataMember()> Public Property QUIEN As System.String
            <DataMember()> Public Property PAIS As System.String
            <DataMember()> Public Property PROYECTO As System.String
            <DataMember()> Public Property MOTIVO As System.String
            <DataMember()> Public Property CATEGORIA As System.String
            <DataMember()> Public Property DESCRIPCION As System.String

        End Class


#End Region

    End Class

End Namespace

