<%@ Page Language="VB" MasterPageFile="~/fasi/FASI.master" AutoEventWireup="false" %>
<%@ MasterType TypeName="FASI" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <!-- This code was generated by Form Designer v7.1.223.1 at 2019-04-03 12:57:42 PM model release 8, Form Generator v1.0.34.31 -->
    <!-- Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. -->
    
    <!-- Bootstrap -->
    <link rel='stylesheet' href='/fasi/assets/css/ladda-themeless.min.css' />
    <link rel='stylesheet' href='/fasi/assets/css/bootstrap-datetimepicker.min.css' />
    <link rel='stylesheet' href='/fasi/assets/css/bootstrap-table.min.css' />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
   <![endif]-->
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceholder1" runat="Server">
    <div class="ibox">
     <div class="ibox-content">
        <form id="H5CotizacionMiAutoaDoradoMainForm">
            <input type="hidden" id="H5CotizacionMiAutoaDoradoFormId" name="H5CotizacionMiAutoaDoradoFormId" value="" />
            <div id="alerts-container"></div>
			<div class="row">
            <!-- Container content -->
                        <!-- Container: Genralinformation zone -->
                        <div  class='col-md-12 row'>

                  <div id="Genralinformation">
                    <div class='col-md-12'><h5 class='sectionTitle-solid' ></h5></div>
    <!-- Container content -->
                <!-- ProductCode dropdownlist -->
                <div class='col-md-2 form-vertical'>
                  <div class='form-group'>
                    <label id='ProductCodeLabel' class='control-label' for='ProductCode'>Producto</label>
                        <select id='ProductCode' name='ProductCode' class='form-control' title='Código del producto.' disabled='disabled'>
                                </select>

                  </div>
                </div>
                <!-- EffectiveDate datepicker -->
                <div class='col-md-2 form-vertical'>
                  <div class='form-group'>
                    <label id='EffectiveDateLabel' class='control-label' for='EffectiveDate'>Fecha de efecto</label>
                        <div class='input-group date' id='EffectiveDate_group'>
                                    <input id='EffectiveDate' name='EffectiveDate' type='text' class='form-control' title='Fecha de efecto (inicio de vigencia) de la póliza o certificado.' size='10' maxlength='10'/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                  </div>
                </div>
                <!-- uwcaseid text -->
                <div class='col-md-2 form-vertical'>
                  <div class='form-group'>
                    <label id='uwcaseidLabel' class='control-label hidden' for='uwcaseid'>Caso en tratamiento</label>
                        <p id='uwcaseid' name='uwcaseid' class='form-control-static@Control.Class@'></p>
                  </div>
                </div>
                <!-- LineOfBusiness dropdownlist -->
                <div class='col-md-2 form-vertical'>
                  <div class='form-group'>
                    <label id='LineOfBusinessLabel' class='control-label hidden' for='LineOfBusiness'>Ramo</label><span id='LineOfBusinessRequired' class='required-mark hidden'>*</span>
                        <select id='LineOfBusiness' name='LineOfBusiness' class='form-control hidden' title='Código del ramo comercial.' disabled='disabled'>
                                </select>

                  </div>
                </div>
    <!-- End Container content -->
               </div>
                        </div>
                        <!-- End Container: Genralinformation zone -->
                        <!-- Container: tabcontainer0 tabcontainer -->
                        <div  class='col-md-12'>

               <div class='tabs-container'>
                  <ul class='nav nav-tabs'>
                     <li class='active'>
                        <a id='tab1' href='#tab1Panel' data-toggle='tab'title=''>INFORMACIÓN BÁSICA</a>
                     </li>
                     <li>
                        <a id='tab0' href='#tab0Panel' data-toggle='tab'title='' class='hidden'>INFORMACIÓN ADICIONAL</a>
                     </li>
                     <li>
                        <a id='tab2Direccion' href='#tab2DireccionPanel' data-toggle='tab'title='' class='hidden'>DIRECCIÓN</a>
                     </li>
                     <li>
                        <a id='tab2Pago' href='#tab2PagoPanel' data-toggle='tab'title='' class='hidden'>PAGO</a>
                     </li>
                   </ul>
                       <div class='tab-content'>
                      <div class='tab-pane active' id='tab1Panel'>
                        <div class='panel-body'>
<h5>Incluya la información mínima necesaria para realizar el cálculo de la prima y presione el botón "Cotizar". Si está de acuerdo con la prima mostrada, presione el botón "Guardar y seguir".  Recuerde que los campos marcados con asterisco son de entrada obligatoria.</h5>
    <!-- Container content -->
                <!-- Container: zone13 zone -->
                <div  class='col-md-6 row'>

                  <div id="zone13">
    <!-- Container content -->
                <!-- Container: IBAsegurado zone -->
                <div  class='col-md-12 row'>

                  <div id="IBAsegurado">
                    <div class='col-md-12'><h5 class='sectionTitle-solid' >Asegurado</h5></div>
    <!-- Container content -->
                <!-- BirthdateIncluded datepicker -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='BirthdateIncludedLabel' class='control-label' for='BirthdateIncluded'>Fecha de nacimiento</label><span id='BirthdateIncludedRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <div class='input-group date' id='BirthdateIncluded_group'>
                                    <input id='BirthdateIncluded' name='BirthdateIncluded' type='text' class='form-control' title='Fecha de nacimiento del cliente.' size='10' maxlength='10'/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                    </div>
                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: IBAsegurado zone -->
                <!-- Container: IBVehiculo zone -->
                <div  class='col-md-12 row'>

                  <div id="IBVehiculo">
                    <div class='col-md-12'><h5 class='sectionTitle-solid' >Vehículo</h5></div>
    <!-- Container content -->
                <!-- YearOfManufactured numeric -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='YearOfManufacturedLabel' class='control-label' for='YearOfManufactured'>Año</label><span id='YearOfManufacturedRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='YearOfManufactured' name='YearOfManufactured' title='Año de Fabricación' type='text' style='text-align: right'/>
                    </div>
                  </div>
                </div>
                <!-- VehicleCode dropdownlist -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='VehicleCodeLabel' class='control-label' for='VehicleCode'>Vehículo</label><span id='VehicleCodeRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <select id='VehicleCode' name='VehicleCode' class='form-control' title='Código del Vehículo'>
                                </select>

                    </div>
                  </div>
                </div>
                <!-- ValueOfTheVehicle numeric -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='ValueOfTheVehicleLabel' class='control-label' for='ValueOfTheVehicle'>Valor</label><span id='ValueOfTheVehicleRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                    <div class='col-xs-12 input-group'>    <input class='form-control' id='ValueOfTheVehicle' name='ValueOfTheVehicle' title='Valor del Vehículo' type='text' style='text-align: right'/><span class='input-group-btn'></span>    <select id='Currency' name='Currency' class='form-control' title='Currency' disabled='disabled'>
                                </select>
</div>
                    </div>
                  </div>
                </div>
                <!-- DrivingZone dropdownlist -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='DrivingZoneLabel' class='control-label' for='DrivingZone'>Zona de Circulación</label><span id='DrivingZoneRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <select id='DrivingZone' name='DrivingZone' class='form-control' title='Zona de Circulación'>
                                </select>

                    </div>
                  </div>
                </div>
                <!-- UseOfVehicle dropdownlist -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='UseOfVehicleLabel' class='control-label' for='UseOfVehicle'>Uso</label><span id='UseOfVehicleRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <select id='UseOfVehicle' name='UseOfVehicle' class='form-control' title='Uso del Vehículo'>
                                </select>

                    </div>
                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: IBVehiculo zone -->
                <!-- label7 label -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group text-left'>
                                  <label id='label7' title='label7' style='color: #A5A5A5;'>Una vez que incluya toda la información requerida, presione el botón 'Cotizar' para que pueda visualizar las coberturas y la prima.</label>

                  </div>
                </div>
                <!-- Cotizar button -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group'>
                    <button id='Cotizar' class='ladda-button btn center-block btn-danger' data-style='expand-right' title='Calcula el monto de prima anual en base a la información incluida.' ><span class='ladda-label'>
Cotizar   <img src='/images/Library/16x16_ASPNetIcons/settings1_16x16.gif' id='CotizarImage' /></span><span class='ladda-spinner'></span></button>

                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone13 zone -->
                <!-- Container: TcoverCollection zone -->
                <div  class='col-md-6 row'>

                  <div id="TcoverCollection">
                    <div class='col-md-12'><h5 class='sectionTitle-solid' >Coberturas y prima</h5></div>
    <!-- Container content -->
                <!-- Container: CoverageWithCalculatedPremium grid -->
                <div  class='col-md-12'>

               <div id='CoverageWithCalculatedPremiumContainer'>
                    <div id='CoverageWithCalculatedPremiumTblPlaceHolder'></div>
               </div>

                </div>
                <!-- End Container: CoverageWithCalculatedPremium grid -->
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: TcoverCollection zone -->
                <!-- Continuar button -->
                <div class='col-md-6 form-vertical'>
                  <div class='form-group'>
                    <button id='Continuar' class='ladda-button btn pull-right hidden btn-success' data-style='expand-right' title='Acepta la cotización. Pasa a completar la información faltante.' ><span class='ladda-label'>
Guardar y seguir   <img src='/images/Library/16x16_ASPNetIcons/ok_16x16.gif' id='ContinuarImage' /></span><span class='ladda-spinner'></span></button>

                  </div>
                </div>
    <!-- End Container content -->
                        </div>
                      </div>
                      <div class='tab-pane' id='tab0Panel'>
                        <div class='panel-body'>
<h5>Inculya la información adicional, tanto del asegurado como del vehículo. Recuerde que los campos marcados con asterisco son de entrada obligatoria.</h5>
    <!-- Container content -->
                <!-- Container: IABase zone -->
                <div  class='col-md-12 row'>

                  <div id="IABase">
    <!-- Container content -->
                <!-- Container: IAAsegurado zone -->
                <div  class='col-md-6 row'>

                  <div id="IAAsegurado">
                    <div class='col-md-12'><h5 class='sectionTitle-solid' >Asegurado</h5></div>
    <!-- Container content -->
                <!-- ClientID text -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='ClientIDLabel' class='control-label' for='ClientID'>Identificación</label><span id='ClientIDRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='ClientID' name='ClientID' title='Código de Cliente' type='text' size='14' maxlength='14'/>
                    </div>
                  </div>
                </div>
                <!-- FirstName text -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='FirstNameLabel' class='control-label' for='FirstName'>Nombre(s)</label><span id='FirstNameRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='FirstName' name='FirstName' title='Nombre(s) del cliente.' type='text' size='20' maxlength='20'/>
                    </div>
                  </div>
                </div>
                <!-- LastName text -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='LastNameLabel' class='control-label' for='LastName'>Apellido paterno</label><span id='LastNameRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='LastName' name='LastName' title='Apellido paterno del cliente.' type='text' size='20' maxlength='20'/>
                    </div>
                  </div>
                </div>
                <!-- LastName2 text -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='LastName2Label' class='control-label' for='LastName2'>Apellido materno</label><span id='LastName2Required' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='LastName2' name='LastName2' title='Apellido materno del cliente.' type='text' size='20' maxlength='20'/>
                    </div>
                  </div>
                </div>
                <!-- Gender radiobuttonlist -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='GenderLabel' class='control-label' for='Gender'>Sexo</label><span id='GenderRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                                <div id='GenderWrap'>
                <div class='radio'>
                  <label><input type='radio' name='Gender' id='Gender_1' title='Sexo del cliente' value='1' />                  <span >Femenino</span>
                </label>
                </div>
                <div class='radio'>
                  <label><input type='radio' name='Gender' id='Gender_2' value='2' />                  <span >Masculino</span>
                </label>
                </div>
                <div id='Gender_validate'></div>
            </div>

                    </div>
                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: IAAsegurado zone -->
                <!-- Container: IAVehiculo zone -->
                <div  class='col-md-6 row'>

                  <div id="IAVehiculo">
                    <div class='col-md-12'><h5 class='sectionTitle-solid' >Vehículo</h5></div>
    <!-- Container content -->
                <!-- LicensePlateType dropdownlist -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='LicensePlateTypeLabel' class='control-label' for='LicensePlateType'>Tipo de Matrícula</label><span id='LicensePlateTypeRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <select id='LicensePlateType' name='LicensePlateType' class='form-control' title='Tipo de Matrícula'>
                                </select>

                    </div>
                  </div>
                </div>
                <!-- LicensePlate text -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='LicensePlateLabel' class='control-label' for='LicensePlate'>Matrícula</label><span id='LicensePlateRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='LicensePlate' name='LicensePlate' title='Licencia' type='text' size='10' maxlength='10'/>
                    </div>
                  </div>
                </div>
                <!-- Color text -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='ColorLabel' class='control-label' for='Color'>Color</label><span id='ColorRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='Color' name='Color' title='Color' type='text' size='15' maxlength='15'/>
                    </div>
                  </div>
                </div>
                <!-- Chassis text -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='ChassisLabel' class='control-label' for='Chassis'>Chasis</label><span id='ChassisRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='Chassis' name='Chassis' title='Chasis' type='text' size='40' maxlength='40'/>
                    </div>
                  </div>
                </div>
                <!-- EngineSerialNumber text -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='EngineSerialNumberLabel' class='control-label' for='EngineSerialNumber'>Motor</label><span id='EngineSerialNumberRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='EngineSerialNumber' name='EngineSerialNumber' title='Serial del Motor' type='text' size='40' maxlength='40'/>
                    </div>
                  </div>
                </div>
                <!-- Mileage numeric -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='MileageLabel' class='control-label' for='Mileage'>Kilometraje</label>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='Mileage' name='Mileage' title='Kilometraje' type='text' style='text-align: right'/>
                    </div>
                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: IAVehiculo zone -->
                <!-- button3 button -->
                <div class='col-md-6 form-vertical'>
                  <div class='form-group'>
                    <button id='button3' class='ladda-button btn pull-right btn-success' data-style='expand-right' title='' ><span class='ladda-label'>
Guardar y seguir   <img src='/images/Library/16x16_ASPNetIcons/ok_16x16.gif' id='button3Image' /></span><span class='ladda-spinner'></span></button>

                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: IABase zone -->
    <!-- End Container content -->
                        </div>
                      </div>
                      <div class='tab-pane' id='tab2DireccionPanel'>
                        <div class='panel-body'>
    <!-- Container content -->
                <!-- physicaladdress1 PhysicalAddress -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                                    <!-- ADDRESS CONTROL CONTAINER CONTENT -->
                                <div id="physicaladdress1AddressControl" style="display: none">
                                    <!-- Form -->
                                    <div id="physicaladdress1FormContent">

                                        <!--sRecType-->
                                        <div class='form-group' id="physicaladdress1TypeOfAddressForClient">
                                            <div class='col-md-4 text-left'>
                                              <label id='physicaladdress1sRecTypeLabel' class='control-label' for='physicaladdress1sRecType'><%=GetGlobalResourceObject("AddressControl", "AddressType")%></label>
                                            </div>
                                            <div class='col-md-8'>
                                                <select class='form-control' id='physicaladdress1sRecType' name='physicaladdress1sRecType' title='<%=GetGlobalResourceObject("AddressControl", "AddressType")%>'>
                                                    <option value="1"><%=GetGlobalResourceObject("AddressControl", "AddressTypeComercial")%></option>
                                                    <option value="2"><%=GetGlobalResourceObject("AddressControl", "AddressTypeParticular")%></option>
                                                    <option value="3"><%=GetGlobalResourceObject("AddressControl", "AddressTypePOBox")%></option>
                                                </select>
                                            </div>
                                        </div>

                                        <!--Country-->
                                        <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='physicaladdress1CountryLabel' class='control-label' for='physicaladdress1Country'><%=GetGlobalResourceObject("AddressControl", "Country")%></label>
                                            </div>
                                            <div class='col-md-8'>
                                                <select class='form-control' id='physicaladdress1Country' name='physicaladdress1Country' title='<%=GetGlobalResourceObject("AddressControl", "Country")%>'></select>
                                            </div>
                                        </div>

                                        <!--Street-->
                                        <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='physicaladdress1StreetLabel' class='control-label' for='physicaladdress1StreetOrUrl'><%=GetGlobalResourceObject("AddressControl", "StreetOrUrl")%></label>
                                            </div>
                                            <div class='col-md-8'>
                                                <div class="input-group">
                                                    <input class='form-control' id='physicaladdress1StreetOrUrl' name='physicaladdress1StreetOrUrl' maxlength="45" title='<%=GetGlobalResourceObject("AddressControl", "StreetOrUrl")%>' type='text'/>
                                                    <% If (Convert.ToBoolean(ConfigurationManager.AppSettings("ShowMapOnAddressService"))) Then %>
                                                        <span id="physicaladdress1ShowMapBtn" class="input-group-addon" title="<%=GetGlobalResourceObject("AddressControl", "ShowMap")%>"><i class="fa fa-search" aria-hidden="true"></i></span>
                                                    <% Else %>
                                                        <span class="input-group-addon"></span>
                                                    <% End If %>
                                                </div>
                                                <input class='form-control' id='physicaladdress1Street' name='physicaladdress1Street' maxlength="45" title='<%=GetGlobalResourceObject("AddressControl", "Street")%>' type='text'/>
                                            </div>
                                        </div>

                                        <!--Postal code-->
                                        <div class='form-group' id="physicaladdress1ZipCodeContainer">
                                            <div class='col-md-4 text-left'>
                                              <label id='physicaladdress1ZipCodeLabel' class='control-label' for='physicaladdress1ZipCode'><%=GetGlobalResourceObject("AddressControl", "ZipCode")%></label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='physicaladdress1ZipCode' name='physicaladdress1ZipCode' maxlength="10" title='<%=GetGlobalResourceObject("AddressControl", "ZipCode")%>' type='text'/>
                                            </div>
                                        </div>

                                        <!--Postal code ARG-->
                                        <div class='form-group' id="physicaladdress1ZipCodeARGContainer">
                                            <div class='col-md-4 text-left'>
                                              <label id='physicaladdress1ZipCodeARGLabel' class='control-label' for='physicaladdress1ZipCodeARG'><%=GetGlobalResourceObject("AddressControl", "ZipCodeARG")%></label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='physicaladdress1ZipCodeARG' name='physicaladdress1ZipCodeARG' maxlength="8" title='<%=GetGlobalResourceObject("AddressControl", "ZipCodeARG")%>' type='text'/>
                                            </div>
                                        </div>

                                        <!--Province-->
                                        <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='physicaladdress1ProvinceLabel' class='control-label' for='physicaladdress1Province'><%=GetGlobalResourceObject("AddressControl", "Province")%></label>
                                            </div>
                                            <div class='col-md-8'>
                                                <select class='form-control' id='physicaladdress1Province' name='physicaladdress1Province' title='<%=GetGlobalResourceObject("AddressControl", "Province")%>'></select>
                                            </div>
                                        </div>

                                        <!--Locality-->
                                        <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='physicaladdress1LocalityLabel' class='control-label' for='physicaladdress1Locality'><%=GetGlobalResourceObject("AddressControl", "Locality")%></label>
                                            </div>
                                            <div class='col-md-8'>
                                                <select class='form-control' id='physicaladdress1Locality' name='physicaladdress1Locality' title='<%=GetGlobalResourceObject("AddressControl", "Locality")%>'></select>
                                            </div>
                                        </div>

                                        <!--Municipality-->
                                        <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='physicaladdress1MunicipalityLabel' class='control-label' for='physicaladdress1Municipality'><%=GetGlobalResourceObject("AddressControl", "Municipality")%></label>
                                            </div>
                                            <div class='col-md-8'>
                                                <select class='form-control' id='physicaladdress1Municipality' name='physicaladdress1Municipality' title='<%=GetGlobalResourceObject("AddressControl", "Municipality")%>'></select>
                                            </div>
                                        </div>

                                        <!--Email-->
                                        <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='physicaladdress1EmailLabel' class='control-label' for='physicaladdress1Email'><%=GetGlobalResourceObject("AddressControl", "Email")%></label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='physicaladdress1Email' placeholder='<%=GetGlobalResourceObject("AddressControl", "EmailPlaceholder")%>' maxlength="60" name='physicaladdress1Email' title='<%=GetGlobalResourceObject("AddressControl", "Email")%>' type='text'/>
                                            </div>
                                        </div>
                                        
                                        <br />

                                        <!-- Address toolbar -->
                                        <div class='form-group'>
                                            <div class='col-md-12 text-right'>
                                                <div id="physicaladdress1AddressToolbar">
                                                    <button id="physicaladdress1AddAddressBtn" type="button" class="btn btn-primary" data-modal-title="Add" style="display: none" title="<%=GetGlobalResourceObject("AddressControl", "AddAddress")%>">
                                                        <i class="fa fa-plus"></i> <%=GetGlobalResourceObject("AddressControl", "AddAddress")%></button>
                                                    <button id="physicaladdress1UpdateAddressBtn" type="button" class="btn btn-primary" data-modal-title="Update" style="display: none" title="<%=GetGlobalResourceObject("AddressControl", "UpdateAddress")%>">
                                                        <i class="fa fa-pencil"></i> <%=GetGlobalResourceObject("AddressControl", "UpdateAddress")%></button>
                                                    <button id="physicaladdress1DeleteAddressBtn" type="button" class="btn btn-danger hidden" data-modal-title="Delete" title="<%=GetGlobalResourceObject("AddressControl", "DeleteAddress")%>">
                                                        <i class="fa fa-trash"></i> <%=GetGlobalResourceObject("AddressControl", "DeleteAddress")%></button>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- End of address toolbar -->

                                        <div id="physicaladdress1PhoneWrapper">
                                            <hr />

                                            <!-- Teléfonos -->
                                            <div class='form-group'>
                                                <div class="col-xs-12" id="physicaladdress1PhonesContainer"></div>
                                            </div>

                                            <br />

                                            <!-- Phone toolbar -->
                                            <div class='form-group'>
                                                <div class='col-md-12 text-right'>
                                                    <div id="physicaladdress1PhoneToolbar">
                                                        <button id="physicaladdress1AddPhoneBtn" type="button" class="btn btn-primary" data-modal-title="Add" title=" <%=GetGlobalResourceObject("AddressControl", "AddPhone")%>">
                                                            <i class="fa fa-plus"></i> <%=GetGlobalResourceObject("AddressControl", "AddPhone")%></button>
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- End of address toolbar -->
                                        </div>
                                    </div>
                                    <!-- End of Form -->                                   

                                    <input type="hidden" id="physicaladdress1Latitude" value="" />
                                    <input type="hidden" id="physicaladdress1Longitude" value="" />
                                    <input type="hidden" id="physicaladdress1NRecOwner" value="" />
                                    <input type="hidden" id="physicaladdress1EffectiveDate" value="" />
                                    <input type="hidden" id="physicaladdress1IsPhoneAvailable" value="" />
                                    <input type="hidden" id="physicaladdress1LocalCountry" value="" />
                                    <input type="hidden" id="physicaladdress1KeyToAddressRecord" value="" />
                                    <input type="hidden" id="physicaladdress1IsCalledFromBackOffice" value="" />
      
                                    <!-- MODALS -->
                                    <!-- Delete address modal -->
                                    <div id="physicaladdress1DeleteAdddressModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
                                       <div class="modal-dialog">
                                          <div class="modal-content">
                                             <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                <h4 class="modal-title"><%=GetGlobalResourceObject("AddressControl", "DeleteMessageTitle")%></h4>
                                             </div>
                                             <div class="modal-body">
                                                <p class="error-text"><%=GetGlobalResourceObject("AddressControl", "DeleteMessageBody")%></p>
                                             </div>
                                             <div class="modal-footer">
                                                <button id="physicaladdress1DeleteAddressModalBtn" class="btn btn-danger" data-dismiss="modal" title="<%=GetGlobalResourceObject("AddressControl", "Delete")%>">
                                                    <i class="fa fa-trash"></i> <%=GetGlobalResourceObject("AddressControl", "Delete")%></button>
                                                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true" title="<%=GetGlobalResourceObject("AddressControl", "Cancel")%>">
                                                    <i class="fa fa-times"></i> <%=GetGlobalResourceObject("AddressControl", "Cancel")%></button>
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                    <!-- End of delete address modal -->

                                    <!-- Add address modal -->
                                    <div id='physicaladdress1AddAddressModal' class='modal fade' tabindex='-1' role='dialog' aria-labelledby='edit' aria-hidden='true'>
                                       <div class="modal-dialog">
                                          <div class="modal-content">
                                             <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                <h4 class="modal-title"><%=GetGlobalResourceObject("AddressControl", "AddMessageTitle")%></h4>
                                             </div>
                                             <div class="modal-body">
                                                <p class="error-text"><%=GetGlobalResourceObject("AddressControl", "AddMessageBody")%></p>
                                             </div>
                                             <div class="modal-footer">
                                                <button id="physicaladdress1AddAddressModalBtn" class="btn btn-primary" data-dismiss="modal" title="<%=GetGlobalResourceObject("AddressControl", "Add")%>">
                                                    <i class="fa fa-plus"></i> <%=GetGlobalResourceObject("AddressControl", "Add")%></button>
                                                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true" title="<%=GetGlobalResourceObject("AddressControl", "Cancel")%>">
                                                    <i class="fa fa-times"></i> <%=GetGlobalResourceObject("AddressControl", "Cancel")%></button>
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                    <!-- End of add address modal -->

                                    <!-- Update address modal -->
                                    <div id='physicaladdress1UpdateAddressModal' class='modal fade' tabindex='-1' role='dialog' aria-labelledby='edit' aria-hidden='true'>
                                       <div class="modal-dialog">
                                          <div class="modal-content">
                                             <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                <h4 class="modal-title"><%=GetGlobalResourceObject("AddressControl", "UpdateMessageTitle")%></h4>
                                             </div>
                                             <div class="modal-body">
                                                <p class="error-text"><%=GetGlobalResourceObject("AddressControl", "UpdateAddressMessageBody")%></p>
                                             </div>
                                             <div class="modal-footer">
                                                <button id="physicaladdress1UpdateAddressModalBtn" class="btn btn-primary" data-dismiss="modal" title="<%=GetGlobalResourceObject("AddressControl", "UpdateAddress")%>">
                                                    <i class="fa fa-pencil"></i> <%=GetGlobalResourceObject("AddressControl", "UpdateAddress")%></button>
                                                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true" title="<%=GetGlobalResourceObject("AddressControl", "Cancel")%>">
                                                    <i class="fa fa-times"></i> <%=GetGlobalResourceObject("AddressControl", "Cancel")%></button>
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                    <!-- End of update address modal -->

                                    <!-- Delete Phone modal -->
                                    <div id="physicaladdress1DeletePhoneModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
                                       <div class="modal-dialog">
                                          <div class="modal-content">
                                             <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                <h4 class="modal-title"><%=GetGlobalResourceObject("AddressControl", "DeleteMessageTitle")%></h4>
                                             </div>
                                             <div class="modal-body">
                                                <p class="error-text"><%=GetGlobalResourceObject("AddressControl", "DeleteMessageBody")%></p>
                                             </div>
                                             <div class="modal-footer">
                                                <button id="physicaladdress1DeletePhoneModalBtn" class="btn btn-danger" data-dismiss="modal" title="<%=GetGlobalResourceObject("AddressControl", "DeletePhone")%>">
                                                    <i class="fa fa-trash"></i> <%=GetGlobalResourceObject("AddressControl", "DeletePhone")%></button>
                                                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true" title="<%=GetGlobalResourceObject("AddressControl", "Cancel")%>">
                                                    <i class="fa fa-times"></i> <%=GetGlobalResourceObject("AddressControl", "Cancel")%></button>
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                    <!-- End of delete Phone modal -->

                                    <!-- Add Phone modal -->
                                    <div id='physicaladdress1AddPhoneModal' class='modal fade' tabindex='-1' role='dialog' aria-labelledby='edit' aria-hidden='true'>
                                       <div class="modal-dialog">
                                          <div class="modal-content">
                                             <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                <h4 class="modal-title"><%=GetGlobalResourceObject("AddressControl", "AddMessageTitle")%></h4>
                                             </div>
                                             <div class="modal-body">
                                                <p class="error-text"><%=GetGlobalResourceObject("AddressControl", "AddMessageBody")%></p>
                                             </div>
                                             <div class="modal-footer">
                                                <button id="physicaladdress1AddPhoneModalBtn" class="btn btn-primary" data-dismiss="modal" title="<%=GetGlobalResourceObject("AddressControl", "Add")%>">
                                                    <i class="fa fa-plus"></i> <%=GetGlobalResourceObject("AddressControl", "Add")%></button>
                                                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true" title="<%=GetGlobalResourceObject("AddressControl", "Cancel")%>">
                                                    <i class="fa fa-times"></i> <%=GetGlobalResourceObject("AddressControl", "Cancel")%></button>
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                    <!-- End of add Phone modal -->

                                    <!-- Update Phone modal -->
                                    <div id='physicaladdress1UpdatePhoneModal' class='modal fade' tabindex='-1' role='dialog' aria-labelledby='edit' aria-hidden='true'>
                                       <div class="modal-dialog">
                                          <div class="modal-content">
                                             <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                <h4 class="modal-title"><%=GetGlobalResourceObject("AddressControl", "UpdateMessageTitle")%></h4>
                                             </div>
                                             <div class="modal-body">
                                                <p class="error-text"><%=GetGlobalResourceObject("AddressControl", "UpdatePhoneMessageBody")%></p>
                                             </div>
                                             <div class="modal-footer">
                                                <button id="physicaladdress1UpdatePhoneModalBtn" class="btn btn-primary" data-dismiss="modal" title="<%=GetGlobalResourceObject("AddressControl", "UpdatePhone")%>">
                                                    <i class="fa fa-pencil"></i> <%=GetGlobalResourceObject("AddressControl", "UpdatePhone")%></button>
                                                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true" title="<%=GetGlobalResourceObject("AddressControl", "Cancel")%>">
                                                    <i class="fa fa-times"></i> <%=GetGlobalResourceObject("AddressControl", "Cancel")%></button>
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                    <!-- End of update addressPhone modal -->

                                    <!-- Map modal-->
                                    <div id='physicaladdress1MapModal' class='modal fade' tabindex='-1' role='dialog' aria-labelledby='edit' aria-hidden='true'>
                                       <div class="modal-dialog modal-lg">
                                          <div class="modal-content">
                                             <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                <h4 class="modal-title"><%=GetGlobalResourceObject("AddressControl", "MapTitle")%></h4>
                                             </div>
                                             <div class="modal-body">
                                                 <div class="row">
                                                     <!-- Container content -->
                                                     <% If (Convert.ToBoolean(ConfigurationManager.AppSettings("ShowMapOnAddressService"))) Then %>
                                                         <div class='form-group'>
                                                             <div class="col-md-12">
                                                                 <input id="physicaladdress1Autocomplete" class="form-control" name="physicaladdress1Autocomplete" type="text" placeholder="<%=GetGlobalResourceObject("AddressControl", "SearchAddress")%>" title="<%=GetGlobalResourceObject("AddressControl", "SearchAddress")%>"/>
                                                                 <div id="physicaladdress1Map" style="height:300px"></div>                
                                                             </div>
                                                         </div>
                                                    <% End If %>
                                                    <!-- End Container content -->
                                                </div>
                                             </div>
                                             <div class="modal-footer">
                                                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true" title="<%=GetGlobalResourceObject("AddressControl", "Close")%>">
                                                    <i class="fa fa-times"></i> <%=GetGlobalResourceObject("AddressControl", "Close")%></button>
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                    <!-- end of map modal -->
                                    <!-- END OF MODALS -->
                                </div>
                                <!-- END OF ADDRESS CONTROL CONTAINER CONTENT -->

                    </div>
                  </div>
                </div>
                <!-- Container: zone9 zone -->
                <div  class='col-md-12'>

                  <div id="zone9">
    <!-- Container content -->
                <!-- buttonGSdireccion button -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group'>
                    <button id='buttonGSdireccion' class='ladda-button btn pull-right btn-success' data-style='expand-right' title='Acepta la información relacionada con la dirección del asegurado.' ><span class='ladda-label'>
Guardar y seguir   <img src='/images/Library/16x16_ASPNetIcons/ok_16x16.gif' id='buttonGSdireccionImage' /></span><span class='ladda-spinner'></span></button>

                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone9 zone -->
    <!-- End Container content -->
                        </div>
                      </div>
                      <div class='tab-pane' id='tab2PagoPanel'>
                        <div class='panel-body'>
    <!-- Container content -->
                <!-- Container: zone3 zone -->
                <div  class='col-md-12 row'>

                  <div id="zone3">
                    <div class='col-md-12'><h5 class='sectionTitle-solid' >TARJETA DE CRÉDITO</h5></div>
<h5>Inculya la información del pago. Recuerde que los campos marcados con asterisco son de entrada obligatoria.</h5>
    <!-- Container content -->
                <!-- label0 label -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group text-left'>
                                  <label id='label0' title='label0'>Los datos que se indican a continuación corresponden a la tarjeta de crédito a utilizar para realizar el pago de la primera prima. Una vez emitida la póliza, nuestro personal se pondrá en contacto con el asegurado a fin de establecer el medio de pago que se utilizará en los pagos posteriores.</label>

                  </div>
                </div>
                <!-- Container: zone2 zone -->
                <div  class='col-md-12 row'>

                  <div id="zone2">
    <!-- Container content -->
                <!-- Container: zone0 zone -->
                <div  class='col-md-6 row'>

                  <div id="zone0">
    <!-- Container content -->
                <!-- CreditCardType radiobuttonlist -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-2 text-left'>
                      <label id='CreditCardTypeLabel' class='control-label' for='CreditCardType'></label><span id='CreditCardTypeRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-10'>
                                <div id='CreditCardTypeWrap'>
                <div id='CreditCardType_Dynamic'>
                </div>
                <div id='CreditCardType_validate'></div>
            </div>

                    </div>
                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone0 zone -->
                <!-- Container: zone10 zone -->
                <div  class='col-md-6'>

                  <div id="zone10">
    <!-- Container content -->
                <!-- BankCode dropdownlist -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='BankCodeLabel' class='control-label' for='BankCode'>Banco</label><span id='BankCodeRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <select id='BankCode' name='BankCode' class='form-control' title='Banco al que pertenece la tarjeta'>
                                </select>

                    </div>
                  </div>
                </div>
                <!-- CreditCardNumber text -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='CreditCardNumberLabel' class='control-label' for='CreditCardNumber'>Número</label><span id='CreditCardNumberRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='CreditCardNumber' name='CreditCardNumber' title='Tarjeta de Crédito' type='text' size='20' maxlength='20'/>
                    </div>
                  </div>
                </div>
                <!-- MonthCard numeric -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='MonthCardLabel' class='control-label' for='MonthCard'>Vencimiento</label><span id='MonthCardRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                    <div class='col-xs-12 input-group'>                            <div class='input-group'>
    <input class='form-control' id='MonthCard' name='MonthCard' title='Mes de vencimiento de la tarjeta' type='text' style='text-align: right'/>                            <div class='input-group-addon'>/</div>
                            </div>
<span class='input-group-btn'></span>    <input class='form-control' id='YearCard' name='YearCard' title='Año de vencimiento de la tarjeta' type='text' style='text-align: right'/></div>
                    </div>
                  </div>
                </div>
                <!-- AuthorizationNumber numeric -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='AuthorizationNumberLabel' class='control-label' for='AuthorizationNumber'>Autorización</label><span id='AuthorizationNumberRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='AuthorizationNumber' name='AuthorizationNumber' title='Número de Autorización' type='text' style='text-align: right'/>
                    </div>
                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone10 zone -->
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone2 zone -->
                <!-- Accept button -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group'>
                    <button id='Accept' class='ladda-button btn pull-right btn-success' data-style='expand-right' title='Registrar la cotización, a la espera de confirmación por parte de la empresa de seguros.' ><span class='ladda-label'>
Guardar y seguir   <img src='/images/Library/16x16_ASPNetIcons/ok_16x16.gif' id='AcceptImage' /></span><span class='ladda-spinner'></span></button>

                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone3 zone -->
    <!-- End Container content -->
                        </div>
                      </div>
                   </div>
					</div>
                        </div>
                        <!-- End Container: tabcontainer0 tabcontainer -->
                        <!-- Container: zone4 zone -->
                        <div  class='col-md-12 row'>

                  <div id="zone4" class='hidden' >
    <!-- Container content -->
                <!-- Container: zone6 zone -->
                <div  class='col-md-12 row'>

                  <div id="zone6">
    <!-- Container content -->
                <!-- Container: zone8 zone -->
                <div  class='col-md-12 row'>

                  <div id="zone8">
    <!-- Container content -->
                <!-- Container: zone14 zone -->
                <div  class='col-md-3 row'>

                  <div id="zone14">
    <!-- Container content -->
                <!-- button1 button -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group'>
                    <button id='button1' class='ladda-button btn center-block btn-success' data-style='expand-right' title='' ><span class='ladda-label'>
Enviar cotización al correo electrónico   <img src='/images/Library/16x16_ASPNetIcons/mail1_16x16.gif' id='button1Image' /></span><span class='ladda-spinner'></span></button>

                  </div>
                </div>
                <!-- eMail text -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group'>
                    <label id='eMailLabel' class='control-label' for='eMail'></label><span id='eMailRequired' class='required-mark'>*</span>
                        <input class='form-control' id='eMail' name='eMail' title='Correo electrónico al que se le será enviada la información de la cotización' type='text' placeholder='usuario@proveedor.com' size='60' maxlength='60'/>
                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone14 zone -->
                <!-- button0 button -->
                <div class='col-md-3 form-vertical'>
                  <div class='form-group'>
                    <button id='button0' class='ladda-button btn center-block btn-success' data-style='expand-right' title='' ><span class='ladda-label'>
Ver resumen de la cotización   <img src='/images/Library/16x16_ASPNetIcons/zoom_in_16x16.gif' id='button0Image' /></span><span class='ladda-spinner'></span></button>

                  </div>
                </div>
                <!-- button2 button -->
                <div class='col-md-3 form-vertical'>
                  <div class='form-group'>
                    <button id='button2' class='ladda-button btn center-block btn-success' data-style='expand-right' title='' ><span class='ladda-label'>
Guardar temporalmente   <img src='/images/Library/16x16_ASPNetIcons/data_16x16.gif' id='button2Image' /></span><span class='ladda-spinner'></span></button>

                  </div>
                </div>
                <!-- Container: zone15 zone -->
                <div  class='col-md-3 row'>

                  <div id="zone15">
    <!-- Container content -->
                <!-- button4 button -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group'>
                    <button id='button4' class='ladda-button btn center-block btn-danger' data-style='expand-right' title='' ><span class='ladda-label'>
Comprar la póliza   <img src='/images/Library/16x16_ASPNetIcons/shopping_cart_16x16.gif' id='button4Image' /></span><span class='ladda-spinner'></span></button>

                  </div>
                </div>
                <!-- OnLinePrintIndicator checkbox -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='OnLinePrintIndicatorWrap'>
    <div class='checkbox'>
                                    <label id='OnLinePrintIndicatorLabel'>
                                        <input id='OnLinePrintIndicator' name='OnLinePrintIndicator' type='checkbox' title=''  />
                               <span >Ver cuadro de póliza en línea</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone15 zone -->
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone8 zone -->
                <!-- Container: zone1 zone -->
                <div  class='col-md-12 row'>

                  <div id="zone1" class='hidden' >
    <!-- Container content -->
                <!-- MailToProducerIndicator checkbox -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='MailToProducerIndicatorWrap'>
    <div class='checkbox'>
                                    <label id='MailToProducerIndicatorLabel'>
                                        <input id='MailToProducerIndicator' name='MailToProducerIndicator' type='checkbox' title='En caso afirmativo, se envía una copia de la cotización al intermediario'  />
                               <span >Enviar información de la cotización al intermediario</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- eMailSend text -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-2 text-left'>
                      <label id='eMailSendLabel' class='control-label hidden' for='eMailSend'></label><span id='eMailSendRequired' class='required-mark hidden'>*</span>
                    </div>
                    <div class='col-md-10'>
                        <input class='form-control hidden' id='eMailSend' name='eMailSend' title='Dirección del correo electrónico del cliente' type='text' placeholder='usuario@proveedor.com' disabled='disabled' size='15' maxlength='15'/>
                    </div>
                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone1 zone -->
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone6 zone -->
                <!-- Container: zone5 zone -->
                <div  class='col-md-12 row'>

                  <div id="zone5">
                    <div class='col-md-12'><h5 class='sectionTitle-solid' >AVISO</h5></div>
    <!-- Container content -->
                <!-- label5 label -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group text-left'>
                                  <label id='label5' title='label5'>Esta cotización se emite a modo puramente referencial, a partir de los datos suministrados en línea; por lo tanto, la suma asegurada, tasas y demás rubros aquí previstos, pueden ser objeto de modificación con base en la documentación que efectivamente presente el Propuesto Tomador al solicitar formalmente la contratación de la póliza, la cual también dependerá de los resultados de la inspección del vehículo.</label>

                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone5 zone -->
    <!-- End Container content -->
               </div>
                        </div>
                        <!-- End Container: zone4 zone -->
                        <!-- Container: botonesmenu zone -->
                        <div  class='col-md-12 row'>

                  <div id="botonesmenu" class='hidden' >
    <!-- Container content -->
                <!-- Cerrar button -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group'>
                    <button id='Cerrar' class='ladda-button btn pull-right btn-danger' data-style='expand-right' title='El cliente no desea registrar la cotización. Finaliza el proceso.' ><span class='ladda-label'>
Salir sin guardar   <img src='/images/Library/16x16_ASPNetIcons/delete_16x16.gif' id='CerrarImage' /></span><span class='ladda-spinner'></span></button>

                  </div>
                </div>
    <!-- End Container content -->
               </div>
                        </div>
                        <!-- End Container: botonesmenu zone -->
            <!-- End Container content -->

            </div>
        </form>



        <div id='CoverageWithCalculatedPremiumPopup' class='modal fade' tabindex='-1' role='dialog' aria-labelledby='edit' aria-hidden='true'>
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title"><span>Información</span></h4>
                    </div>
                    <div class="modal-body">
                      <div class="row">
                        <form id='CoverageWithCalculatedPremiumEditForm'>
                            <!-- Container content -->
                                        <!-- SelectedByDefault checkbox -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='SelectedByDefaultLabel' class='control-label' for='SelectedByDefault'>Sel</label>
                                            </div>
                                            <div class='col-md-8'>
                                                        <div id='SelectedByDefaultWrap'>
    <div class='checkbox'>
                                                    <label id='SelectedByDefaultLabel'>
                                                        <input id='SelectedByDefault' name='SelectedByDefault' type='checkbox' title='Seleccionado por Defecto'  />
                                                    </label>
                                                </div>
            </div>

                                            </div>
                                          </div>
                                        </div>
                                        <!-- DescriptionCover text -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='DescriptionCoverLabel' class='control-label' for='DescriptionCover'>Cobertura</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='DescriptionCover' name='DescriptionCover' title='Descripción de la cobertura.' type='text' size='120' maxlength='120'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- InsuredAmountCover numeric -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='InsuredAmountCoverLabel' class='control-label' for='InsuredAmountCover'>Capital asegurado</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='InsuredAmountCover' name='InsuredAmountCover' title='Capital Asegurado' type='text' style='text-align: right'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- AnnualPremiumCover numeric -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='AnnualPremiumCoverLabel' class='control-label' for='AnnualPremiumCover'>Prima anual</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='AnnualPremiumCover' name='AnnualPremiumCover' title='Monto de prima' type='text' style='text-align: right'/>
                                            </div>
                                          </div>
                                        </div>
                            <!-- End Container content -->

                        </form>
                      </div>
                    </div>
                    <div class="modal-footer">
                        <button id="CoverageWithCalculatedPremiumSaveBtn"  class="btn btn-warning">Guardar</button>
                        <button class="btn"  data-dismiss="modal" aria-hidden="true">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>


    </div>
  </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="footer" runat="Server">
    <script src='/fasi/assets/js/spin.min.js'></script>
    <script src='/fasi/assets/js/ladda.min.js'></script>
    <script src='/fasi/assets/js/ladda.jquery.min.js'></script>
    <script src='/fasi/assets/js/bootstrap-datetimepicker.min.js'></script>
    <script src='/fasi/assets/js/bootstrap-table.min.js'></script>
    <script src='/fasi/assets/js/bootstrap-table-es-CR.min.js'></script>
    <script src='/fasi/app/js/TableHelper.js?rel=20190403125742923'></script>
    <script src='https://maps.googleapis.com/maps/api/js?key=AIzaSyDs6FAyd0OFweXJiR360F-bovr-lXSYQGA&libraries=places'></script>
    <script src='/fasi/app/js/address-support.js'></script>
    <script src='/fasi/app/js/map-handling.js'></script>
    <script src='/fasi/assets/js/autoNumeric.min.js'></script>


    <script src="H5CotizacionMiAutoaDorado.js?rel=20190403125742923"></script>
 
</asp:Content>