<%@ Page Language="VB" MasterPageFile="~/fasi/FASI.master" AutoEventWireup="false" %>
<%@ MasterType TypeName="FASI" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <!-- This code was generated by Form Designer v7.3.24.1 at 2019-11-08 03:13:32 p. m. model release 2, Form Generator v1.0.37.9 -->
    <!-- Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. -->
    
    <!-- Bootstrap -->
    <link rel='stylesheet' href='/fasi/assets/css/bootstrap-datetimepicker.min.css' />
    <link rel='stylesheet' href='/fasi/assets/css/bootstrap-table.min.css' />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
   <![endif]-->
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceholder1" runat="Server">
    <div class="ibox">
     <div class="ibox-content">
        <form id="H5MantRequerimientosPorRolMainForm">
            <input type="hidden" id="H5MantRequerimientosPorRolFormId" name="H5MantRequerimientosPorRolFormId" value="" />
            <div id="alerts-container"></div>
			<div class="row">
            <!-- Container content -->
                        <!-- Container: TabRequirementTypeByRole_Grid grid -->
                        <div  class='col-md-12'>

                       <div id='TabRequirementTypeByRole_GridContainer'>
                            <div id="TabRequirementTypeByRole_Gridtoolbar">
                            <div class='form-inline'>
                                <button id="TabRequirementTypeByRole_GridCreateBtn" type="button" class="btn btn-default" data-modal-title="Agregar">
                                    Agregar
                                </button>
                                <button id="TabRequirementTypeByRole_GridRemoveBtn"  type="button" class="btn btn-danger" disabled data-title="Eliminar">
                                    <i class="glyphicon glyphicon-remove"></i>Eliminar
                                </button>
                            </div>
                            </div>
                            <div id='TabRequirementTypeByRole_GridTblPlaceHolder'></div>
                       </div>

                        </div>
                        <!-- End Container: TabRequirementTypeByRole_Grid grid -->
            <!-- End Container content -->

            </div>
        </form>



        <div id='TabRequirementTypeByRole_GridPopup' class='modal fade' tabindex='-1' role='dialog' aria-labelledby='edit' aria-hidden='true'>
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title"><span>Información</span></h4>
                    </div>
                    <div class="modal-body">
                      <div class="row">
                        <form id='TabRequirementTypeByRole_GridEditForm'>
                            <!-- Container content -->
                                        <!-- RequirementType dropdownlist -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='RequirementTypeLabel' class='control-label' for='RequirementType'>Requisito o requerimiento</label><span id='RequirementTypeRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <select id='RequirementType' name='RequirementType' class='form-control' title='Tipo de requisito'>
                                                </select>

                                            </div>
                                          </div>
                                        </div>
                                        <!-- RoleCode dropdownlist -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='RoleCodeLabel' class='control-label' for='RoleCode'>Rol o Figura</label><span id='RoleCodeRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <select id='RoleCode' name='RoleCode' class='form-control' title='Código del rol o figura.'>
                                                </select>

                                            </div>
                                          </div>
                                        </div>
                                        <!-- CreationDate datepicker -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='CreationDateLabel' class='control-label hidden' for='CreationDate'>Creado en</label><span id='CreationDateRequired' class='required-mark hidden'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <div class='input-group date hidden' id='CreationDate_group'>
                                                    <input id='CreationDate' name='CreationDate' type='text' class='form-control hidden' title='Fecha del computador en que se crea el registro.' size='19' maxlength='19'/>
                                                    <span class='input-group-addon'>
                                                        <span class='glyphicon glyphicon-calendar'></span>
                                                    </span>
                                                </div>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- CreatorUserCode numeric -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='CreatorUserCodeLabel' class='control-label hidden' for='CreatorUserCode'>Creado por</label><span id='CreatorUserCodeRequired' class='required-mark hidden'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control hidden' id='CreatorUserCode' name='CreatorUserCode' title='Código del usuario que crea el registro.' type='text' style='text-align: right'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- UpdateDate datepicker -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='UpdateDateLabel' class='control-label hidden' for='UpdateDate'>Última actualización por</label><span id='UpdateDateRequired' class='required-mark hidden'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <div class='input-group date hidden' id='UpdateDate_group'>
                                                    <input id='UpdateDate' name='UpdateDate' type='text' class='form-control hidden' title='Fecha del computador en que se crea o actualiza el registro.' size='19' maxlength='19'/>
                                                    <span class='input-group-addon'>
                                                        <span class='glyphicon glyphicon-calendar'></span>
                                                    </span>
                                                </div>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- UpdateUserCode numeric -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='UpdateUserCodeLabel' class='control-label hidden' for='UpdateUserCode'>Última actualización en</label><span id='UpdateUserCodeRequired' class='required-mark hidden'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control hidden' id='UpdateUserCode' name='UpdateUserCode' title='Código del usuario que crea o actualiza el registro.' type='text' style='text-align: right'/>
                                            </div>
                                          </div>
                                        </div>
                            <!-- End Container content -->

                        </form>
                      </div>
                    </div>
                    <div class="modal-footer">
                        <button id="TabRequirementTypeByRole_GridSaveBtn"  class="btn btn-warning">Guardar</button>
                        <button class="btn"  data-dismiss="modal" aria-hidden="true">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>


    </div>
  </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="footer" runat="Server">
    <script src='/fasi/assets/js/bootstrap-datetimepicker.min.js'></script>
    <script src='/fasi/assets/js/bootstrap-table.min.js'></script>
    <script src='/fasi/assets/js/bootstrap-table-es-CR.min.js'></script>
    <script src='/fasi/app/js/TableHelper.js?rel=20191108031332869'></script>
    <script src='/fasi/assets/js/bootstrap-table-export.js'></script>
    <script src='/fasi/assets/js/tableExport.min.js'></script>
    <script src='/fasi/assets/js/pdfmake.min.js'></script>
    <script src='/fasi/assets/js/vfs_fonts.js'></script>
    <script src='/fasi/assets/js/jquery.base64.js'></script>
    <script src='/fasi/assets/js/autoNumeric.min.js'></script>


    <script src="H5MantRequerimientosPorRol.js?rel=20191108031332869"></script>
 
</asp:Content>