<%@ Page Language="VB" MasterPageFile="~/fasi/FASI.master" AutoEventWireup="false" %>
<%@ MasterType TypeName="FASI" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <!-- This code was generated by Form Designer v7.3.25.1 at 2019-11-11 03:34:59 p. m. model release 1, Form Generator v1.0.37.10 -->
    <!-- Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. -->
    
    <!-- Bootstrap -->
    <link rel='stylesheet' href='/fasi/assets/css/bootstrap-datetimepicker.min.css' />
    <link rel='stylesheet' href='/fasi/assets/css/bootstrap-table.min.css' />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
   <![endif]-->
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceholder1" runat="Server">
    <div class="ibox">
     <div class="ibox-content">
        <form id="H5MantTiposDeRequisitosMainForm">
            <input type="hidden" id="H5MantTiposDeRequisitosFormId" name="H5MantTiposDeRequisitosFormId" value="" />
            <div id="alerts-container"></div>
			<div class="row">
            <!-- Container content -->
                        <!-- Container: TabRequirementType_Grid grid -->
                        <div  class='col-md-12'>

                       <div id='TabRequirementType_GridContainer'>
                            <div id="TabRequirementType_Gridtoolbar">
                            <div class='form-inline'>
                                <button id="TabRequirementType_GridCreateBtn" type="button" class="btn btn-default" data-modal-title="Agregar">
                                    Agregar
                                </button>
                                <button id="TabRequirementType_GridRemoveBtn"  type="button" class="btn btn-danger" disabled data-title="Eliminar">
                                    <i class="glyphicon glyphicon-remove"></i>Eliminar
                                </button>
                <!-- ShowTranslatorGrid button -->
                  <div class='form-group'>
                    <button id='ShowTranslatorGrid' class='ladda-button btn pull-left btn-default' data-style='expand-right' title='Mostrar Vista Traducción' ><span class='ladda-label'>Vista Traducción</span><span class='ladda-spinner'></span></button>

                  </div>
                            </div>
                            </div>
                            <div id='TabRequirementType_GridTblPlaceHolder'></div>
                       </div>

                        </div>
                        <!-- End Container: TabRequirementType_Grid grid -->
                        <!-- Container: TabRequirementTypeTranslator_Grid grid -->
                        <div  class='col-md-12'>

                       <div id='TabRequirementTypeTranslator_GridContainer' class='hidden'>
                            <div id="TabRequirementTypeTranslator_Gridtoolbar">
                            <div class='form-inline'>
                <!-- ShowStandardGrid button -->
                  <div class='form-group'>
                    <button id='ShowStandardGrid' class='ladda-button btn pull-left btn-default' data-style='expand-right' title='Mostrar Vista Estándar' ><span class='ladda-label'>Vista Estándar</span><span class='ladda-spinner'></span></button>

                  </div>
                            </div>
                            </div>
                            <div id='TabRequirementTypeTranslator_GridTblPlaceHolder' class='hidden'></div>
                       </div>

                        </div>
                        <!-- End Container: TabRequirementTypeTranslator_Grid grid -->
                        <!-- Container: zoneStandardToolBar zone -->
                        <div  class='col-md-12'>

                        </div>
                        <!-- End Container: zoneStandardToolBar zone -->
                        <!-- Container: zoneTranslatorToolBar zone -->
                        <div  class='col-md-12'>

                        </div>
                        <!-- End Container: zoneTranslatorToolBar zone -->
            <!-- End Container content -->

            </div>
        </form>



        <div id='TabRequirementType_GridPopup' class='modal fade' tabindex='-1' role='dialog' aria-labelledby='edit' aria-hidden='true'>
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title"><span>Información</span></h4>
                    </div>
                    <div class="modal-body">
                      <div class="row">
                        <form id='TabRequirementType_GridEditForm'>
                            <!-- Container content -->
                                        <!-- RequirementType numeric -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='RequirementTypeLabel' class='control-label' for='RequirementType'>ID</label><span id='RequirementTypeRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='RequirementType' name='RequirementType' title='Tipo requisito.' type='text' style='text-align: right'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- Description text -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='DescriptionLabel' class='control-label' for='Description'>Nombre</label><span id='DescriptionRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='Description' name='Description' title='Descripción del código.' type='text' size='60' maxlength='60'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- ShortDescription text -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='ShortDescriptionLabel' class='control-label' for='ShortDescription'>Descripción breve</label><span id='ShortDescriptionRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='ShortDescription' name='ShortDescription' title='Descripción abreviada del código.' type='text' size='20' maxlength='20'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- LineOfBusiness dropdownlist -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='LineOfBusinessLabel' class='control-label' for='LineOfBusiness'>Ramo</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <select id='LineOfBusiness' name='LineOfBusiness' class='form-control' title='Ramo al que pertenece'>
                                                </select>

                                            </div>
                                          </div>
                                        </div>
                                        <!-- Product dropdownlist -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='ProductLabel' class='control-label' for='Product'>Producto</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <select id='Product' name='Product' class='form-control' title='Código del producto'>
                                                </select>

                                            </div>
                                          </div>
                                        </div>
                                        <!-- RecordStatus dropdownlist -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='RecordStatusLabel' class='control-label' for='RecordStatus'>Estado del registro</label><span id='RecordStatusRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <select id='RecordStatus' name='RecordStatus' class='form-control' title='Estado del registro.'>
                                                </select>

                                            </div>
                                          </div>
                                        </div>
                                        <!-- ProcessType dropdownlist -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='ProcessTypeLabel' class='control-label' for='ProcessType'>Procesado por</label><span id='ProcessTypeRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <select id='ProcessType' name='ProcessType' class='form-control' title='Tipo de Forma en que se procesa un requisito: por un wf, por un humano, etc'>
                                                </select>

                                            </div>
                                          </div>
                                        </div>
                                        <!-- UnderwritingArea dropdownlist -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='UnderwritingAreaLabel' class='control-label' for='UnderwritingArea'>Área de suscripción</label><span id='UnderwritingAreaRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <select id='UnderwritingArea' name='UnderwritingArea' class='form-control' title='Área de suscripción: financiera, médica, etc'>
                                                </select>

                                            </div>
                                          </div>
                                        </div>
                                        <!-- Payer dropdownlist -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='PayerLabel' class='control-label' for='Payer'>Pagador</label><span id='PayerRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <select id='Payer' name='Payer' class='form-control' title='Pagador del requisito'>
                                                </select>

                                            </div>
                                          </div>
                                        </div>
                                        <!-- Cost numeric -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='CostLabel' class='control-label' for='Cost'>Costo</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='Cost' name='Cost' title='Costo del requisito' type='text' style='text-align: right'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- Link text -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='LinkLabel' class='control-label' for='Link'>Url</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='Link' name='Link' title='Url de la planilla del requisito' type='text' size='256' maxlength='256'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- AcordRequirementCode numeric -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='AcordRequirementCodeLabel' class='control-label' for='AcordRequirementCode'>Código Acord</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='AcordRequirementCode' name='AcordRequirementCode' title='Código Requisito Acord.' type='text' style='text-align: right'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- CreatorUserCode numeric -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='CreatorUserCodeLabel' class='control-label hidden' for='CreatorUserCode'>Creado por</label><span id='CreatorUserCodeRequired' class='required-mark hidden'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control hidden' id='CreatorUserCode' name='CreatorUserCode' title='Código del usuario que crea el registro.' type='text' style='text-align: right'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- CreationDate datepicker -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='CreationDateLabel' class='control-label hidden' for='CreationDate'>Creado en</label><span id='CreationDateRequired' class='required-mark hidden'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <div class='input-group date hidden' id='CreationDate_group'>
                                                    <input id='CreationDate' name='CreationDate' type='text' class='form-control hidden' title='Fecha del computador en que se crea el registro.' size='19' maxlength='19'/>
                                                    <span class='input-group-addon'>
                                                        <span class='glyphicon glyphicon-calendar'></span>
                                                    </span>
                                                </div>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- UpdateUserCode numeric -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='UpdateUserCodeLabel' class='control-label hidden' for='UpdateUserCode'>Última actualización por</label><span id='UpdateUserCodeRequired' class='required-mark hidden'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control hidden' id='UpdateUserCode' name='UpdateUserCode' title='Usuario que actualizó por última vez el registro.' type='text' style='text-align: right'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- UpdateDate datepicker -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='UpdateDateLabel' class='control-label hidden' for='UpdateDate'>Última actualización en</label><span id='UpdateDateRequired' class='required-mark hidden'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <div class='input-group date hidden' id='UpdateDate_group'>
                                                    <input id='UpdateDate' name='UpdateDate' type='text' class='form-control hidden' title='Fecha que se actualizó por última vez el registro.' size='19' maxlength='19'/>
                                                    <span class='input-group-addon'>
                                                        <span class='glyphicon glyphicon-calendar'></span>
                                                    </span>
                                                </div>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- AllowViewRequirement checkbox -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='AllowViewRequirementLabel' class='control-label' for='AllowViewRequirement'>Mostrar botón para visualizar un documento</label>
                                            </div>
                                            <div class='col-md-8'>
                                                        <div id='AllowViewRequirementWrap'>
    <div class='checkbox'>
                                                    <label id='AllowViewRequirementLabel'>
                                                        <input id='AllowViewRequirement' name='AllowViewRequirement' type='checkbox' title='Indica si se debe mostrar el botón para mostrar un documento.'  />
                                                    </label>
                                                </div>
            </div>

                                            </div>
                                          </div>
                                        </div>
                                        <!-- AllowLoadRequirement checkbox -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='AllowLoadRequirementLabel' class='control-label' for='AllowLoadRequirement'>Mostrar botón para cargar un documento</label>
                                            </div>
                                            <div class='col-md-8'>
                                                        <div id='AllowLoadRequirementWrap'>
    <div class='checkbox'>
                                                    <label id='AllowLoadRequirementLabel'>
                                                        <input id='AllowLoadRequirement' name='AllowLoadRequirement' type='checkbox' title='Indica si se debe mostrar el botón para cargar un documento.'  />
                                                    </label>
                                                </div>
            </div>

                                            </div>
                                          </div>
                                        </div>
                            <!-- End Container content -->

                        </form>
                      </div>
                    </div>
                    <div class="modal-footer">
                        <button id="TabRequirementType_GridSaveBtn"  class="btn btn-warning">Guardar</button>
                        <button class="btn"  data-dismiss="modal" aria-hidden="true">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
        <div id='TabRequirementTypeTranslator_GridPopup' class='modal fade' tabindex='-1' role='dialog' aria-labelledby='edit' aria-hidden='true'>
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title"><span>Información</span></h4>
                    </div>
                    <div class="modal-body">
                      <div class="row">
                        <form id='TabRequirementTypeTranslator_GridEditForm'>
                            <!-- Container content -->
                                        <!-- RequirementTypeTranslator numeric -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='RequirementTypeTranslatorLabel' class='control-label' for='RequirementTypeTranslator'>Tipo requisito</label><span id='RequirementTypeTranslatorRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='RequirementTypeTranslator' name='RequirementTypeTranslator' title='Tipo de Requisito' type='text' style='text-align: right'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- LanguageIdTranslator dropdownlist -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='LanguageIdTranslatorLabel' class='control-label' for='LanguageIdTranslator'>Idioma</label><span id='LanguageIdTranslatorRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <select id='LanguageIdTranslator' name='LanguageIdTranslator' class='form-control' title='Idioma en el que se encuentra la descripción'>
                                                </select>

                                            </div>
                                          </div>
                                        </div>
                                        <!-- DescriptionTranslator text -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='DescriptionTranslatorLabel' class='control-label' for='DescriptionTranslator'>Descripción</label><span id='DescriptionTranslatorRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='DescriptionTranslator' name='DescriptionTranslator' title='Descripción del código.' type='text' size='60' maxlength='60'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- ShortDescriptionTranslator text -->
                                        <div class='col-md-6 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='ShortDescriptionTranslatorLabel' class='control-label' for='ShortDescriptionTranslator'>Descripción breve</label><span id='ShortDescriptionTranslatorRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='ShortDescriptionTranslator' name='ShortDescriptionTranslator' title='Descripción abreviada del código.' type='text' size='20' maxlength='20'/>
                                            </div>
                                          </div>
                                        </div>
                            <!-- End Container content -->

                        </form>
                      </div>
                    </div>
                    <div class="modal-footer">
                        <button id="TabRequirementTypeTranslator_GridSaveBtn"  class="btn btn-warning">Guardar</button>
                        <button class="btn"  data-dismiss="modal" aria-hidden="true">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>


    </div>
  </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="footer" runat="Server">
    <script src='/fasi/assets/js/bootstrap-datetimepicker.min.js'></script>
    <script src='/fasi/assets/js/bootstrap-table.min.js'></script>
    <script src='/fasi/assets/js/bootstrap-table-es-CR.min.js'></script>
    <script src='/fasi/app/js/TableHelper.js?rel=20191111033459140'></script>
    <script src='/fasi/assets/js/bootstrap-table-export.js'></script>
    <script src='/fasi/assets/js/tableExport.min.js'></script>
    <script src='/fasi/assets/js/pdfmake.min.js'></script>
    <script src='/fasi/assets/js/vfs_fonts.js'></script>
    <script src='/fasi/assets/js/jquery.base64.js'></script>
    <script src='/fasi/assets/js/autoNumeric.min.js'></script>


    <script src="H5MantTiposDeRequisitos.js?rel=20191111033459140"></script>
 
</asp:Content>