'---------------------------------------------------------------------------------------------------
' <generated>
'     This code was generated by Form Designer v7.3.24.1 at 2019-11-08 04:28:05 p. m. model release 1, Form Generator v1.0.37.9
'     
'     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
' </generated>
'---------------------------------------------------------------------------------------------------
      
#Region "using"

Imports System.Data
Imports System.Globalization
Imports System.Runtime.Serialization
Imports System.Web.Script.Services
Imports System.Web.Services
Imports InMotionGIT.Common.Helpers
Imports InMotionGIT.Common.Proxy
Imports InMotionGIT.FrontOffice.Support

#End Region

Namespace dli.forms

    Public Class H5MantTipoElementoActions
        Inherits System.Web.UI.Page

#Region "Actions Methods"
  

        <WebMethod()>
        Public Shared Function TabDiscountOrExtraPremium_GridTblDataLoad(filter As String, TransDiscountOrExtraPremiumLanguageId1 As String) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            Dim response As Object = New With {.DiscountOrExtraPremiumType = 0, .RecordStatus = 0, .CreatorUserCode = 0, .CreationDate = Date.MinValue, .UpdateUserCode = 0, .UpdateDate = Date.MinValue, .Description = String.Empty, .ShortDescription = String.Empty}
            Dim selectDataTableItem As DataTable
            Dim responseList As New List(Of Object)
            
            
            Try
                InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")

                With New DataManagerFactory("SELECT TABDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE, TABDISCOUNTOREXTRAPREMIUM.RECORDSTATUS, TABDISCOUNTOREXTRAPREMIUM.CREATORUSERCODE, TABDISCOUNTOREXTRAPREMIUM.CREATIONDATE, TABDISCOUNTOREXTRAPREMIUM.UPDATEUSERCODE, TABDISCOUNTOREXTRAPREMIUM.UPDATEDATE, TRANSDISCOUNTOREXTRAPREMIUM.DESCRIPTION, TRANSDISCOUNTOREXTRAPREMIUM.SHORTDESCRIPTION FROM TABDISCOUNTOREXTRAPREMIUM TABDISCOUNTOREXTRAPREMIUM  LEFT JOIN TRANSDISCOUNTOREXTRAPREMIUM TRANSDISCOUNTOREXTRAPREMIUM ON TRANSDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE = TABDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE  AND TRANSDISCOUNTOREXTRAPREMIUM.LANGUAGEID = @:LANGUAGEID1", "TabDiscountOrExtraPremium", "Linked.Underwriting")
                    .AddParameter("LANGUAGEID1", DbType.AnsiString, 5, (TransDiscountOrExtraPremiumLanguageId1 = String.Empty), TransDiscountOrExtraPremiumLanguageId1)

                    selectDataTableItem = .QueryExecuteToTable(True)
                End With
                With selectDataTableItem
                    If Not IsNothing(.Rows) AndAlso .Rows.Count > 0 Then
                        For Each itemData As DataRow In .Rows
                            response = New With {.DiscountOrExtraPremiumType = itemData.NumericValue("DISCOUNTOREXTRAPREMIUMTYPE"), .RecordStatus = itemData.NumericValue("RECORDSTATUS"), .CreatorUserCode = itemData.NumericValue("CREATORUSERCODE"), .CreationDate = itemData.DateTimeValue("CREATIONDATE"), .UpdateUserCode = itemData.NumericValue("UPDATEUSERCODE"), .UpdateDate = itemData.DateTimeValue("UPDATEDATE"), .Description = itemData.StringValue("DESCRIPTION"), .ShortDescription = itemData.StringValue("SHORTDESCRIPTION")}
                            
                            responseList.Add(response)
                        Next

                        With resultData
                            .Count = responseList.Count
                            .Data = responseList
                        End With
                    End If
                End With
            
            If responseList.Count <> 0 Then          
		    
            End If
                
            Catch ex As Exception            
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "TabDiscountOrExtraPremium_GridTblDataLoad", String.Empty)
            End Try
            
            Return resultData
        End Function

        <WebMethod()>
        Public Shared Function TabDiscountOrExtraPremium_Grid1InsertCommandActionTabDiscountOrExtraPremium(DISCOUNTOREXTRAPREMIUMTYPE1 As Decimal, RECORDSTATUS2 As Decimal, CREATORUSERCODE2 As Decimal, UPDATEUSERCODE4 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                With New DataManagerFactory("INSERT INTO TabDiscountOrExtraPremium (DISCOUNTOREXTRAPREMIUMTYPE, RECORDSTATUS, CREATORUSERCODE, CREATIONDATE, UPDATEUSERCODE, UPDATEDATE) VALUES (@:DISCOUNTOREXTRAPREMIUMTYPE1, @:RECORDSTATUS2, @:CREATORUSERCODE2, @:CREATIONDATE3, @:UPDATEUSERCODE4, @:UPDATEDATE5)", "TabDiscountOrExtraPremium", "Linked.Underwriting")
                    .AddParameter("DISCOUNTOREXTRAPREMIUMTYPE1", DbType.Decimal, 0, False, DISCOUNTOREXTRAPREMIUMTYPE1)
                    .AddParameter("RECORDSTATUS2", DbType.Decimal, 0, False, RECORDSTATUS2)
                    .AddParameter("CREATORUSERCODE2", DbType.Decimal, 0, False, CREATORUSERCODE2)
                    .AddParameter("CREATIONDATE3", DbType.DateTime, 0, False, Date.Now)
                    .AddParameter("UPDATEUSERCODE4", DbType.Decimal, 0, False, UPDATEUSERCODE4)
                    .AddParameter("UPDATEDATE5", DbType.DateTime, 0, False, Date.Now)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "TabDiscountOrExtraPremium_Grid1InsertCommandActionTabDiscountOrExtraPremium", String.Empty)
            End Try
            
            Return resultData
        End Function
        <WebMethod()>
        Public Shared Function TabDiscountOrExtraPremium_Grid3InsertCommandActionTransDiscountOrExtraPremium(DISCOUNTOREXTRAPREMIUMTYPE1 As Decimal, LANGUAGEID1 As Decimal, DESCRIPTION3 As String, SHORTDESCRIPTION4 As String, CREATORUSERCODE4 As Decimal, UPDATEUSERCODE6 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                    With New DataManagerFactory("INSERT INTO TransDiscountOrExtraPremium (DISCOUNTOREXTRAPREMIUMTYPE, LANGUAGEID, DESCRIPTION, SHORTDESCRIPTION, CREATORUSERCODE, CREATIONDATE, UPDATEUSERCODE, UPDATEDATE) VALUES (@:DISCOUNTOREXTRAPREMIUMTYPE1, @:LANGUAGEID1, @:DESCRIPTION3, @:SHORTDESCRIPTION4, @:CREATORUSERCODE4, @:CREATIONDATE5, @:UPDATEUSERCODE6, @:UPDATEDATE7)", "TransDiscountOrExtraPremium", "Linked.Underwriting")
                    .AddParameter("DISCOUNTOREXTRAPREMIUMTYPE1", DbType.Decimal, 0, False, DISCOUNTOREXTRAPREMIUMTYPE1)
                    .AddParameter("LANGUAGEID1", DbType.Decimal, 0, False, LANGUAGEID1)
                    .AddParameter("DESCRIPTION3", DbType.AnsiString, 0, (DESCRIPTION3 = String.Empty), DESCRIPTION3)
                    .AddParameter("SHORTDESCRIPTION4", DbType.AnsiString, 0, (SHORTDESCRIPTION4 = String.Empty), SHORTDESCRIPTION4)
                    .AddParameter("CREATORUSERCODE4", DbType.Decimal, 0, False, CREATORUSERCODE4)
                    .AddParameter("CREATIONDATE5", DbType.DateTime, 0, False, Date.Now)
                    .AddParameter("UPDATEUSERCODE6", DbType.Decimal, 0, False, UPDATEUSERCODE6)
                    .AddParameter("UPDATEDATE7", DbType.DateTime, 0, False, Date.Now)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "TabDiscountOrExtraPremium_Grid3InsertCommandActionTransDiscountOrExtraPremium", String.Empty)
            End Try
            
            Return resultData
        End Function

        <WebMethod()>
        Public Shared Function TabDiscountOrExtraPremium_Grid1UpdateCommandActionTabDiscountOrExtraPremium(RECORDSTATUS1 As Decimal, UPDATEUSERCODE1 As Decimal, TabDiscountOrExtraPremiumDiscountOrExtraPremiumType3 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                With New DataManagerFactory("UPDATE TabDiscountOrExtraPremium SET RECORDSTATUS = @:RECORDSTATUS1, UPDATEUSERCODE = @:UPDATEUSERCODE1 WHERE TABDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE = @:DISCOUNTOREXTRAPREMIUMTYPE3", "TabDiscountOrExtraPremium", "Linked.Underwriting")
                    .AddParameter("RECORDSTATUS1", DbType.Decimal, 0, False, RECORDSTATUS1)
                    .AddParameter("UPDATEUSERCODE1", DbType.Decimal, 0, False, UPDATEUSERCODE1)
                    .AddParameter("DISCOUNTOREXTRAPREMIUMTYPE3", DbType.Decimal, 0, False, TabDiscountOrExtraPremiumDiscountOrExtraPremiumType3)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "TabDiscountOrExtraPremium_Grid1UpdateCommandActionTabDiscountOrExtraPremium", String.Empty)
            End Try
            
            Return resultData
        End Function
        <WebMethod()>
        Public Shared Function TabDiscountOrExtraPremium_Grid3SelectCommandActionTransDiscountOrExtraPremium(TransDiscountOrExtraPremiumDiscountOrExtraPremiumType1 As Decimal, TransDiscountOrExtraPremiumLanguageId2 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            Dim response As Object = New With {.Result = 0}
            Dim responseList As New List(Of Object)
            
            Try
                InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")

                With New DataManagerFactory("Select COUNT(TRANSDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE) DISCOUNTOREXTRAPREMIUMTYPE FROM TRANSDISCOUNTOREXTRAPREMIUM TRANSDISCOUNTOREXTRAPREMIUM  WHERE TRANSDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE = @:DISCOUNTOREXTRAPREMIUMTYPE1 AND TRANSDISCOUNTOREXTRAPREMIUM.LANGUAGEID = @:LANGUAGEID2", "TransDiscountOrExtraPremium", "Linked.Underwriting")
                    .AddParameter("DISCOUNTOREXTRAPREMIUMTYPE1", DbType.Decimal, 0, False, TransDiscountOrExtraPremiumDiscountOrExtraPremiumType1)
                    .AddParameter("LANGUAGEID2", DbType.Decimal, 0, False, TransDiscountOrExtraPremiumLanguageId2)

                    response.Result = .QueryExecuteScalarToInteger()
                End With
                With resultData
                    .Count = 1
                    .Data = response
                End With
            
            If responseList.Count <> 0 Then          
		    
            End If
                
            Catch ex As Exception            
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "TabDiscountOrExtraPremium_Grid3SelectCommandActionTransDiscountOrExtraPremium", String.Empty)
            End Try
            
            Return resultData
        End Function
        <WebMethod()>
        Public Shared Function TabDiscountOrExtraPremium_Grid5InsertCommandActionTransDiscountOrExtraPremium(DISCOUNTOREXTRAPREMIUMTYPE1 As Decimal, LANGUAGEID1 As Decimal, DESCRIPTION3 As String, SHORTDESCRIPTION4 As String, CREATORUSERCODE4 As Decimal, UPDATEUSERCODE6 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                        With New DataManagerFactory("INSERT INTO TransDiscountOrExtraPremium (DISCOUNTOREXTRAPREMIUMTYPE, LANGUAGEID, DESCRIPTION, SHORTDESCRIPTION, CREATORUSERCODE, CREATIONDATE, UPDATEUSERCODE, UPDATEDATE) VALUES (@:DISCOUNTOREXTRAPREMIUMTYPE1, @:LANGUAGEID1, @:DESCRIPTION3, @:SHORTDESCRIPTION4, @:CREATORUSERCODE4, @:CREATIONDATE5, @:UPDATEUSERCODE6, @:UPDATEDATE7)", "TransDiscountOrExtraPremium", "Linked.Underwriting")
                    .AddParameter("DISCOUNTOREXTRAPREMIUMTYPE1", DbType.Decimal, 0, False, DISCOUNTOREXTRAPREMIUMTYPE1)
                    .AddParameter("LANGUAGEID1", DbType.Decimal, 0, False, LANGUAGEID1)
                    .AddParameter("DESCRIPTION3", DbType.AnsiString, 0, (DESCRIPTION3 = String.Empty), DESCRIPTION3)
                    .AddParameter("SHORTDESCRIPTION4", DbType.AnsiString, 0, (SHORTDESCRIPTION4 = String.Empty), SHORTDESCRIPTION4)
                    .AddParameter("CREATORUSERCODE4", DbType.Decimal, 0, False, CREATORUSERCODE4)
                    .AddParameter("CREATIONDATE5", DbType.DateTime, 0, False, Date.Now)
                    .AddParameter("UPDATEUSERCODE6", DbType.Decimal, 0, False, UPDATEUSERCODE6)
                    .AddParameter("UPDATEDATE7", DbType.DateTime, 0, False, Date.Now)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "TabDiscountOrExtraPremium_Grid5InsertCommandActionTransDiscountOrExtraPremium", String.Empty)
            End Try
            
            Return resultData
        End Function
        <WebMethod()>
        Public Shared Function TabDiscountOrExtraPremium_Grid6UpdateCommandActionTransDiscountOrExtraPremium(DESCRIPTION1 As String, SHORTDESCRIPTION2 As String, UPDATEUSERCODE2 As Decimal, TransDiscountOrExtraPremiumDiscountOrExtraPremiumType4 As Decimal, TransDiscountOrExtraPremiumLanguageId5 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                        With New DataManagerFactory("UPDATE TransDiscountOrExtraPremium SET DESCRIPTION = @:DESCRIPTION1, SHORTDESCRIPTION = @:SHORTDESCRIPTION2, UPDATEUSERCODE = @:UPDATEUSERCODE2 WHERE TRANSDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE = @:DISCOUNTOREXTRAPREMIUMTYPE4 AND TRANSDISCOUNTOREXTRAPREMIUM.LANGUAGEID = @:LANGUAGEID5", "TransDiscountOrExtraPremium", "Linked.Underwriting")
                    .AddParameter("DESCRIPTION1", DbType.AnsiString, 0, (DESCRIPTION1 = String.Empty), DESCRIPTION1)
                    .AddParameter("SHORTDESCRIPTION2", DbType.AnsiString, 0, (SHORTDESCRIPTION2 = String.Empty), SHORTDESCRIPTION2)
                    .AddParameter("UPDATEUSERCODE2", DbType.Decimal, 0, False, UPDATEUSERCODE2)
                    .AddParameter("DISCOUNTOREXTRAPREMIUMTYPE4", DbType.Decimal, 0, False, TransDiscountOrExtraPremiumDiscountOrExtraPremiumType4)
                    .AddParameter("LANGUAGEID5", DbType.Decimal, 0, False, TransDiscountOrExtraPremiumLanguageId5)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "TabDiscountOrExtraPremium_Grid6UpdateCommandActionTransDiscountOrExtraPremium", String.Empty)
            End Try
            
            Return resultData
        End Function

        <WebMethod()>
        Public Shared Function TabDiscountOrExtraPremium_Grid1DeleteCommandActionTransDiscountOrExtraPremium(TransDiscountOrExtraPremiumDiscountOrExtraPremiumType1 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                With New DataManagerFactory("DELETE FROM TransDiscountOrExtraPremium WHERE TRANSDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE = @:DISCOUNTOREXTRAPREMIUMTYPE1", "TransDiscountOrExtraPremium", "Linked.Underwriting")
                    .AddParameter("DISCOUNTOREXTRAPREMIUMTYPE1", DbType.Decimal, 0, False, TransDiscountOrExtraPremiumDiscountOrExtraPremiumType1)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "TabDiscountOrExtraPremium_Grid1DeleteCommandActionTransDiscountOrExtraPremium", String.Empty)
            End Try
            
            Return resultData
        End Function
        <WebMethod()>
        Public Shared Function TabDiscountOrExtraPremium_Grid3DeleteCommandActionTabDiscountOrExtraPremium(TabDiscountOrExtraPremiumDiscountOrExtraPremiumType1 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                    With New DataManagerFactory("DELETE FROM TabDiscountOrExtraPremium WHERE TABDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE = @:DISCOUNTOREXTRAPREMIUMTYPE1", "TabDiscountOrExtraPremium", "Linked.Underwriting")
                    .AddParameter("DISCOUNTOREXTRAPREMIUMTYPE1", DbType.Decimal, 0, False, TabDiscountOrExtraPremiumDiscountOrExtraPremiumType1)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "TabDiscountOrExtraPremium_Grid3DeleteCommandActionTabDiscountOrExtraPremium", String.Empty)
            End Try
            
            Return resultData
        End Function

        <WebMethod()>
        Public Shared Function TabDiscountOrExtraPremium_Grid2SelectCommandActionTabDiscountOrExtraPremium() As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            Dim response As Object = New With {.Result = 0}
            Dim responseList As New List(Of Object)
            
            Try
                InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")

                With New DataManagerFactory("Select MAX(TABDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE) DISCOUNTOREXTRAPREMIUMTYPE FROM TABDISCOUNTOREXTRAPREMIUM TABDISCOUNTOREXTRAPREMIUM ", "TabDiscountOrExtraPremium", "Linked.Underwriting")

                    response.Result = .QueryExecuteScalarToInteger()
                End With
                With resultData
                    .Count = 1
                    .Data = response
                End With
            
            If responseList.Count <> 0 Then          
		    
            End If
                
            Catch ex As Exception            
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "TabDiscountOrExtraPremium_Grid2SelectCommandActionTabDiscountOrExtraPremium", String.Empty)
            End Try
            
            Return resultData
        End Function

        <WebMethod()>
        Public Shared Function TabDiscountOrExtraPremiumTranslator_GridTblDataLoad(filter As String) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            Dim response As Object = New With {.DiscountOrExtraPremiumType = 0, .LanguageId = 0, .Description = String.Empty, .ShortDescription = String.Empty}
            Dim selectDataTableItem As DataTable
            Dim responseList As New List(Of Object)
            
            
            Try
                InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")

                With New DataManagerFactory("SELECT TABDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE, TRANSDISCOUNTOREXTRAPREMIUM.LANGUAGEID, TRANSDISCOUNTOREXTRAPREMIUM.DESCRIPTION, TRANSDISCOUNTOREXTRAPREMIUM.SHORTDESCRIPTION FROM TABDISCOUNTOREXTRAPREMIUM TABDISCOUNTOREXTRAPREMIUM  LEFT JOIN TRANSDISCOUNTOREXTRAPREMIUM TRANSDISCOUNTOREXTRAPREMIUM ON TRANSDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE = TABDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE ", "TabDiscountOrExtraPremium", "Linked.Underwriting")

                    selectDataTableItem = .QueryExecuteToTable(True)
                End With
                With selectDataTableItem
                    If Not IsNothing(.Rows) AndAlso .Rows.Count > 0 Then
                        For Each itemData As DataRow In .Rows
                            response = New With {.DiscountOrExtraPremiumType = itemData.NumericValue("DISCOUNTOREXTRAPREMIUMTYPE"), .LanguageId = itemData.NumericValue("LANGUAGEID"), .Description = itemData.StringValue("DESCRIPTION"), .ShortDescription = itemData.StringValue("SHORTDESCRIPTION")}
                            
                            responseList.Add(response)
                        Next

                        With resultData
                            .Count = responseList.Count
                            .Data = responseList
                        End With
                    End If
                End With
            
            If responseList.Count <> 0 Then          
		    
            End If
                
            Catch ex As Exception            
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "TabDiscountOrExtraPremiumTranslator_GridTblDataLoad", String.Empty)
            End Try
            
            Return resultData
        End Function

        <WebMethod()>
        Public Shared Function TabDiscountOrExtraPremiumTranslator_Grid1UpdateCommandActionTransDiscountOrExtraPremium(DESCRIPTION1 As String, SHORTDESCRIPTION2 As String, UPDATEUSERCODE2 As Decimal, TransDiscountOrExtraPremiumDiscountOrExtraPremiumType4 As Decimal, TransDiscountOrExtraPremiumLanguageId5 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                With New DataManagerFactory("UPDATE TransDiscountOrExtraPremium SET DESCRIPTION = @:DESCRIPTION1, SHORTDESCRIPTION = @:SHORTDESCRIPTION2, UPDATEUSERCODE = @:UPDATEUSERCODE2 WHERE TRANSDISCOUNTOREXTRAPREMIUM.DISCOUNTOREXTRAPREMIUMTYPE = @:DISCOUNTOREXTRAPREMIUMTYPE4 AND TRANSDISCOUNTOREXTRAPREMIUM.LANGUAGEID = @:LANGUAGEID5", "TransDiscountOrExtraPremium", "Linked.Underwriting")
                    .AddParameter("DESCRIPTION1", DbType.AnsiString, 0, (DESCRIPTION1 = String.Empty), DESCRIPTION1)
                    .AddParameter("SHORTDESCRIPTION2", DbType.AnsiString, 0, (SHORTDESCRIPTION2 = String.Empty), SHORTDESCRIPTION2)
                    .AddParameter("UPDATEUSERCODE2", DbType.Decimal, 0, False, UPDATEUSERCODE2)
                    .AddParameter("DISCOUNTOREXTRAPREMIUMTYPE4", DbType.Decimal, 0, False, TransDiscountOrExtraPremiumDiscountOrExtraPremiumType4)
                    .AddParameter("LANGUAGEID5", DbType.Decimal, 0, False, TransDiscountOrExtraPremiumLanguageId5)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "TabDiscountOrExtraPremiumTranslator_Grid1UpdateCommandActionTransDiscountOrExtraPremium", String.Empty)
            End Try
            
            Return resultData
        End Function


#End Region

#Region "Lookups Web Methods"


        <WebMethod(EnableSession:=True)>
        Public Shared Function LookUpForRecordStatus(id As String) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim result As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True}
            Dim resultData As DataTable = Nothing
            Dim newLookupList As New List(Of InMotionGIT.Common.DataType.LookUpValue)                       
            
            Try
                InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                 
                Dim UserInfo As New InMotionGIT.Membership.Providers.MemberContext
                With New DataManagerFactory(String.Format(CultureInfo.CurrentCulture,
                                                          "SELECT TRIM(ETRANRECORDSTATUS.RECORDSTATUS) RECORDSTATUS, ETRANRECORDSTATUS.DESCRIPTION FROM ETRANRECORDSTATUS ETRANRECORDSTATUS WHERE ETRANRECORDSTATUS.LANGUAGEID = {0} AND NOT ETRANRECORDSTATUS.DESCRIPTION IS NULL ORDER BY DESCRIPTION", InMotionGIT.FASI.Support.Handlers.LanguageHandler.ContextLanguageId()), 
                                            "ETranRecordStatus", "Linked.Common")

                    
                    resultData = .QueryExecuteToTable(True)
                End With

                If Not IsNothing(resultData) Then
                    For Each item As DataRow In resultData.Rows
                        newLookupList.Add(New InMotionGIT.Common.DataType.LookUpValue With {.Code = item.StringValue("RecordStatus"),
                                                                                            .Description = item.StringValue("Description")})
                    Next
                End If

                result.Data = newLookupList

            Catch ex As Exception
                result = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "LookUpForRecordStatus", String.Empty)
            End Try
                        
            Return result
        End Function

        <WebMethod(EnableSession:=True)>
        Public Shared Function LookUpForLanguageIdTranslator(id As String) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim result As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True}
            Dim resultData As DataTable = Nothing
            Dim newLookupList As New List(Of InMotionGIT.Common.DataType.LookUpValue)                       
            
            Try
                InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                 
                Dim UserInfo As New InMotionGIT.Membership.Providers.MemberContext
                With New DataManagerFactory(String.Format(CultureInfo.CurrentCulture,
                                                          "SELECT TRANSLANGUAGE.LANGUAGECODEID, TRANSLANGUAGE.DESCRIPTION FROM TRANSLANGUAGE TRANSLANGUAGE WHERE TRANSLANGUAGE.LANGUAGEID = {0} AND NOT TRANSLANGUAGE.DESCRIPTION IS NULL ORDER BY DESCRIPTION", InMotionGIT.FASI.Support.Handlers.LanguageHandler.ContextLanguageId()), 
                                            "TransLanguage", "Linked.Common")

                    
                    resultData = .QueryExecuteToTable(True)
                End With

                If Not IsNothing(resultData) Then
                    For Each item As DataRow In resultData.Rows
                        newLookupList.Add(New InMotionGIT.Common.DataType.LookUpValue With {.Code = item.NumericValue("LanguageCodeID"),
                                                                                            .Description = item.StringValue("Description")})
                    Next
                End If

                result.Data = newLookupList

            Catch ex As Exception
                result = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantTipoElemento", "LookUpForLanguageIdTranslator", String.Empty)
            End Try
                        
            Return result
        End Function

#End Region

#Region "Form Actions"


#End Region





#Region "Common Utilities"

        Private Shared Sub SetDefaultValuesFromQueryString(formData As EntryData)

        End Sub	


#End Region

#Region "Form Contracts"

        <Serializable()>
        <DataContract()>
        Public Class EntryData

            <DataMember()> Public Property InstanceFormId As String
            <DataMember()> Public Property TabDiscountOrExtraPremiumCollectionDiscountOrExtraPremiumType As System.Double
            <DataMember()> Public Property TabDiscountOrExtraPremiumCollectionRecordStatus As System.Double
            <DataMember()> Public Property TabDiscountOrExtraPremiumCollectionCreatorUserCode As System.Double
            <DataMember()> Public Property TabDiscountOrExtraPremiumCollectionCreationDate As System.DateTime
            <DataMember()> Public Property TabDiscountOrExtraPremiumCollectionUpdateUserCode As System.Double
            <DataMember()> Public Property TabDiscountOrExtraPremiumCollectionUpdateDate As System.DateTime
            <DataMember()> Public Property TabDiscountOrExtraPremiumCollectionDescription As System.String
            <DataMember()> Public Property TabDiscountOrExtraPremiumCollectionShortDescription As System.String
            <DataMember()> Public Property TabDiscountOrExtraPremium_Grid_TabDiscountOrExtraPremium_Item As List(Of TabDiscountOrExtraPremium_Grid_TabDiscountOrExtraPremium_ItemItem)
            <DataMember()> Public Property TabDiscountOrExtraPremiumCollectionLanguageId As System.Double
            <DataMember()> Public Property TabDiscountOrExtraPremiumTranslator_Grid_TabDiscountOrExtraPremium_Item As List(Of TabDiscountOrExtraPremiumTranslator_Grid_TabDiscountOrExtraPremium_ItemItem)

        End Class

        <Serializable()>
        <DataContract()>
        Public Class TabDiscountOrExtraPremium_Grid_TabDiscountOrExtraPremium_ItemItem

            <DataMember()> Public Property DiscountOrExtraPremiumType As System.Double
            <DataMember()> Public Property RecordStatus As System.Double
            <DataMember()> Public Property CreatorUserCode As System.Double
            <DataMember()> Public Property CreationDate As System.DateTime
            <DataMember()> Public Property UpdateUserCode As System.Double
            <DataMember()> Public Property UpdateDate As System.DateTime
            <DataMember()> Public Property Description As System.String
            <DataMember()> Public Property ShortDescription As System.String

        End Class

        <Serializable()>
        <DataContract()>
        Public Class TabDiscountOrExtraPremiumTranslator_Grid_TabDiscountOrExtraPremium_ItemItem

            <DataMember()> Public Property DiscountOrExtraPremiumType As System.Double
            <DataMember()> Public Property LanguageId As System.Double
            <DataMember()> Public Property Description As System.String
            <DataMember()> Public Property ShortDescription As System.String

        End Class


#End Region

    End Class

End Namespace

