'---------------------------------------------------------------------------------------------------
' <generated>
'     This code was generated by Form Designer v7.3.24.1 at 2019-11-08 03:32:17 p. m. model release 1, Form Generator v1.0.37.9
'     
'     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
' </generated>
'---------------------------------------------------------------------------------------------------
      
#Region "using"

Imports System.Data
Imports System.Globalization
Imports System.Runtime.Serialization
Imports System.Web.Script.Services
Imports System.Web.Services
Imports InMotionGIT.Common.Helpers
Imports InMotionGIT.Common.Proxy
Imports InMotionGIT.FrontOffice.Support

#End Region

Namespace dli.forms

    Public Class H5MantEstadoReglasSuscripcionActions
        Inherits System.Web.UI.Page

#Region "Actions Methods"
  

        <WebMethod()>
        Public Shared Function TabUnderwritingRuleSType_GridTblDataLoad(filter As String, TransUnderwritingRuleSTypeLanguageId1 As String) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            Dim response As Object = New With {.UnderwritingRuleStatus = 0, .RecordStatus = 0, .CreatorUserCode = 0, .CreationDate = Date.MinValue, .UpdateUserCode = 0, .UpdateDate = Date.MinValue, .Description = String.Empty, .ShortDescription = String.Empty}
            Dim selectDataTableItem As DataTable
            Dim responseList As New List(Of Object)
            
            
            Try
                InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")

                With New DataManagerFactory("SELECT TABUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS, TABUNDERWRITINGRULESTYPE.RECORDSTATUS, TABUNDERWRITINGRULESTYPE.CREATORUSERCODE, TABUNDERWRITINGRULESTYPE.CREATIONDATE, TABUNDERWRITINGRULESTYPE.UPDATEUSERCODE, TABUNDERWRITINGRULESTYPE.UPDATEDATE, TRANSUNDERWRITINGRULESTYPE.DESCRIPTION, TRANSUNDERWRITINGRULESTYPE.SHORTDESCRIPTION FROM TABUNDERWRITINGRULESTYPE TABUNDERWRITINGRULESTYPE  LEFT JOIN TRANSUNDERWRITINGRULESTYPE TRANSUNDERWRITINGRULESTYPE ON TRANSUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS = TABUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS  AND TRANSUNDERWRITINGRULESTYPE.LANGUAGEID = @:LANGUAGEID1", "TabUnderwritingRuleSType", "Linked.Underwriting")
                    .AddParameter("LANGUAGEID1", DbType.AnsiString, 5, (TransUnderwritingRuleSTypeLanguageId1 = String.Empty), TransUnderwritingRuleSTypeLanguageId1)

                    selectDataTableItem = .QueryExecuteToTable(True)
                End With
                With selectDataTableItem
                    If Not IsNothing(.Rows) AndAlso .Rows.Count > 0 Then
                        For Each itemData As DataRow In .Rows
                            response = New With {.UnderwritingRuleStatus = itemData.NumericValue("UNDERWRITINGRULESTATUS"), .RecordStatus = itemData.NumericValue("RECORDSTATUS"), .CreatorUserCode = itemData.NumericValue("CREATORUSERCODE"), .CreationDate = itemData.DateTimeValue("CREATIONDATE"), .UpdateUserCode = itemData.NumericValue("UPDATEUSERCODE"), .UpdateDate = itemData.DateTimeValue("UPDATEDATE"), .Description = itemData.StringValue("DESCRIPTION"), .ShortDescription = itemData.StringValue("SHORTDESCRIPTION")}
                            
                            responseList.Add(response)
                        Next

                        With resultData
                            .Count = responseList.Count
                            .Data = responseList
                        End With
                    End If
                End With
            
            If responseList.Count <> 0 Then          
		    
            End If
                
            Catch ex As Exception            
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "TabUnderwritingRuleSType_GridTblDataLoad", String.Empty)
            End Try
            
            Return resultData
        End Function

        <WebMethod()>
        Public Shared Function TabUnderwritingRuleSType_Grid1InsertCommandActionTabUnderwritingRuleSType(UNDERWRITINGRULESTATUS1 As Decimal, RECORDSTATUS2 As Decimal, CREATORUSERCODE2 As Decimal, UPDATEUSERCODE4 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                With New DataManagerFactory("INSERT INTO TabUnderwritingRuleSType (UNDERWRITINGRULESTATUS, RECORDSTATUS, CREATORUSERCODE, CREATIONDATE, UPDATEUSERCODE, UPDATEDATE) VALUES (@:UNDERWRITINGRULESTATUS1, @:RECORDSTATUS2, @:CREATORUSERCODE2, @:CREATIONDATE3, @:UPDATEUSERCODE4, @:UPDATEDATE5)", "TabUnderwritingRuleSType", "Linked.Underwriting")
                    .AddParameter("UNDERWRITINGRULESTATUS1", DbType.Decimal, 0, False, UNDERWRITINGRULESTATUS1)
                    .AddParameter("RECORDSTATUS2", DbType.Decimal, 0, False, RECORDSTATUS2)
                    .AddParameter("CREATORUSERCODE2", DbType.Decimal, 0, False, CREATORUSERCODE2)
                    .AddParameter("CREATIONDATE3", DbType.DateTime, 0, False, Date.Now)
                    .AddParameter("UPDATEUSERCODE4", DbType.Decimal, 0, False, UPDATEUSERCODE4)
                    .AddParameter("UPDATEDATE5", DbType.DateTime, 0, False, Date.Now)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "TabUnderwritingRuleSType_Grid1InsertCommandActionTabUnderwritingRuleSType", String.Empty)
            End Try
            
            Return resultData
        End Function
        <WebMethod()>
        Public Shared Function TabUnderwritingRuleSType_Grid3InsertCommandActionTransUnderwritingRuleSType(UNDERWRITINGRULESTATUS1 As Decimal, LANGUAGEID1 As Decimal, DESCRIPTION3 As String, SHORTDESCRIPTION4 As String, CREATORUSERCODE4 As Decimal, UPDATEUSERCODE6 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                    With New DataManagerFactory("INSERT INTO TransUnderwritingRuleSType (UNDERWRITINGRULESTATUS, LANGUAGEID, DESCRIPTION, SHORTDESCRIPTION, CREATORUSERCODE, CREATIONDATE, UPDATEUSERCODE, UPDATEDATE) VALUES (@:UNDERWRITINGRULESTATUS1, @:LANGUAGEID1, @:DESCRIPTION3, @:SHORTDESCRIPTION4, @:CREATORUSERCODE4, @:CREATIONDATE5, @:UPDATEUSERCODE6, @:UPDATEDATE7)", "TransUnderwritingRuleSType", "Linked.Underwriting")
                    .AddParameter("UNDERWRITINGRULESTATUS1", DbType.Decimal, 0, False, UNDERWRITINGRULESTATUS1)
                    .AddParameter("LANGUAGEID1", DbType.Decimal, 0, False, LANGUAGEID1)
                    .AddParameter("DESCRIPTION3", DbType.AnsiString, 0, (DESCRIPTION3 = String.Empty), DESCRIPTION3)
                    .AddParameter("SHORTDESCRIPTION4", DbType.AnsiString, 0, (SHORTDESCRIPTION4 = String.Empty), SHORTDESCRIPTION4)
                    .AddParameter("CREATORUSERCODE4", DbType.Decimal, 0, False, CREATORUSERCODE4)
                    .AddParameter("CREATIONDATE5", DbType.DateTime, 0, False, Date.Now)
                    .AddParameter("UPDATEUSERCODE6", DbType.Decimal, 0, False, UPDATEUSERCODE6)
                    .AddParameter("UPDATEDATE7", DbType.DateTime, 0, False, Date.Now)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "TabUnderwritingRuleSType_Grid3InsertCommandActionTransUnderwritingRuleSType", String.Empty)
            End Try
            
            Return resultData
        End Function

        <WebMethod()>
        Public Shared Function TabUnderwritingRuleSType_Grid1UpdateCommandActionTabUnderwritingRuleSType(RECORDSTATUS1 As Decimal, UPDATEUSERCODE1 As Decimal, TabUnderwritingRuleSTypeUnderwritingRuleStatus3 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                With New DataManagerFactory("UPDATE TabUnderwritingRuleSType SET RECORDSTATUS = @:RECORDSTATUS1, UPDATEUSERCODE = @:UPDATEUSERCODE1 WHERE TABUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS = @:UNDERWRITINGRULESTATUS3", "TabUnderwritingRuleSType", "Linked.Underwriting")
                    .AddParameter("RECORDSTATUS1", DbType.Decimal, 0, False, RECORDSTATUS1)
                    .AddParameter("UPDATEUSERCODE1", DbType.Decimal, 0, False, UPDATEUSERCODE1)
                    .AddParameter("UNDERWRITINGRULESTATUS3", DbType.Decimal, 0, False, TabUnderwritingRuleSTypeUnderwritingRuleStatus3)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "TabUnderwritingRuleSType_Grid1UpdateCommandActionTabUnderwritingRuleSType", String.Empty)
            End Try
            
            Return resultData
        End Function
        <WebMethod()>
        Public Shared Function TabUnderwritingRuleSType_Grid3SelectCommandActionTransUnderwritingRuleSType(TransUnderwritingRuleSTypeUnderwritingRuleStatus1 As Decimal, TransUnderwritingRuleSTypeLanguageId2 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            Dim response As Object = New With {.Result = 0}
            Dim responseList As New List(Of Object)
            
            Try
                InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")

                With New DataManagerFactory("Select COUNT(TRANSUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS) UNDERWRITINGRULESTATUS FROM TRANSUNDERWRITINGRULESTYPE TRANSUNDERWRITINGRULESTYPE  WHERE TRANSUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS = @:UNDERWRITINGRULESTATUS1 AND TRANSUNDERWRITINGRULESTYPE.LANGUAGEID = @:LANGUAGEID2", "TransUnderwritingRuleSType", "Linked.Underwriting")
                    .AddParameter("UNDERWRITINGRULESTATUS1", DbType.Decimal, 0, False, TransUnderwritingRuleSTypeUnderwritingRuleStatus1)
                    .AddParameter("LANGUAGEID2", DbType.Decimal, 0, False, TransUnderwritingRuleSTypeLanguageId2)

                    response.Result = .QueryExecuteScalarToInteger()
                End With
                With resultData
                    .Count = 1
                    .Data = response
                End With
            
            If responseList.Count <> 0 Then          
		    
            End If
                
            Catch ex As Exception            
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "TabUnderwritingRuleSType_Grid3SelectCommandActionTransUnderwritingRuleSType", String.Empty)
            End Try
            
            Return resultData
        End Function
        <WebMethod()>
        Public Shared Function TabUnderwritingRuleSType_Grid5InsertCommandActionTransUnderwritingRuleSType(UNDERWRITINGRULESTATUS1 As Decimal, LANGUAGEID1 As Decimal, DESCRIPTION3 As String, SHORTDESCRIPTION4 As String, CREATORUSERCODE4 As Decimal, UPDATEUSERCODE6 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                        With New DataManagerFactory("INSERT INTO TransUnderwritingRuleSType (UNDERWRITINGRULESTATUS, LANGUAGEID, DESCRIPTION, SHORTDESCRIPTION, CREATORUSERCODE, CREATIONDATE, UPDATEUSERCODE, UPDATEDATE) VALUES (@:UNDERWRITINGRULESTATUS1, @:LANGUAGEID1, @:DESCRIPTION3, @:SHORTDESCRIPTION4, @:CREATORUSERCODE4, @:CREATIONDATE5, @:UPDATEUSERCODE6, @:UPDATEDATE7)", "TransUnderwritingRuleSType", "Linked.Underwriting")
                    .AddParameter("UNDERWRITINGRULESTATUS1", DbType.Decimal, 0, False, UNDERWRITINGRULESTATUS1)
                    .AddParameter("LANGUAGEID1", DbType.Decimal, 0, False, LANGUAGEID1)
                    .AddParameter("DESCRIPTION3", DbType.AnsiString, 0, (DESCRIPTION3 = String.Empty), DESCRIPTION3)
                    .AddParameter("SHORTDESCRIPTION4", DbType.AnsiString, 0, (SHORTDESCRIPTION4 = String.Empty), SHORTDESCRIPTION4)
                    .AddParameter("CREATORUSERCODE4", DbType.Decimal, 0, False, CREATORUSERCODE4)
                    .AddParameter("CREATIONDATE5", DbType.DateTime, 0, False, Date.Now)
                    .AddParameter("UPDATEUSERCODE6", DbType.Decimal, 0, False, UPDATEUSERCODE6)
                    .AddParameter("UPDATEDATE7", DbType.DateTime, 0, False, Date.Now)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "TabUnderwritingRuleSType_Grid5InsertCommandActionTransUnderwritingRuleSType", String.Empty)
            End Try
            
            Return resultData
        End Function
        <WebMethod()>
        Public Shared Function TabUnderwritingRuleSType_Grid6UpdateCommandActionTransUnderwritingRuleSType(DESCRIPTION1 As String, SHORTDESCRIPTION2 As String, UPDATEUSERCODE2 As Decimal, TransUnderwritingRuleSTypeUnderwritingRuleStatus4 As Decimal, TransUnderwritingRuleSTypeLanguageId5 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                        With New DataManagerFactory("UPDATE TransUnderwritingRuleSType SET DESCRIPTION = @:DESCRIPTION1, SHORTDESCRIPTION = @:SHORTDESCRIPTION2, UPDATEUSERCODE = @:UPDATEUSERCODE2 WHERE TRANSUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS = @:UNDERWRITINGRULESTATUS4 AND TRANSUNDERWRITINGRULESTYPE.LANGUAGEID = @:LANGUAGEID5", "TransUnderwritingRuleSType", "Linked.Underwriting")
                    .AddParameter("DESCRIPTION1", DbType.AnsiString, 0, (DESCRIPTION1 = String.Empty), DESCRIPTION1)
                    .AddParameter("SHORTDESCRIPTION2", DbType.AnsiString, 0, (SHORTDESCRIPTION2 = String.Empty), SHORTDESCRIPTION2)
                    .AddParameter("UPDATEUSERCODE2", DbType.Decimal, 0, False, UPDATEUSERCODE2)
                    .AddParameter("UNDERWRITINGRULESTATUS4", DbType.Decimal, 0, False, TransUnderwritingRuleSTypeUnderwritingRuleStatus4)
                    .AddParameter("LANGUAGEID5", DbType.Decimal, 0, False, TransUnderwritingRuleSTypeLanguageId5)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "TabUnderwritingRuleSType_Grid6UpdateCommandActionTransUnderwritingRuleSType", String.Empty)
            End Try
            
            Return resultData
        End Function

        <WebMethod()>
        Public Shared Function TabUnderwritingRuleSType_Grid1DeleteCommandActionTransUnderwritingRuleSType(TransUnderwritingRuleSTypeUnderwritingRuleStatus1 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                With New DataManagerFactory("DELETE FROM TransUnderwritingRuleSType WHERE TRANSUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS = @:UNDERWRITINGRULESTATUS1", "TransUnderwritingRuleSType", "Linked.Underwriting")
                    .AddParameter("UNDERWRITINGRULESTATUS1", DbType.Decimal, 0, False, TransUnderwritingRuleSTypeUnderwritingRuleStatus1)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "TabUnderwritingRuleSType_Grid1DeleteCommandActionTransUnderwritingRuleSType", String.Empty)
            End Try
            
            Return resultData
        End Function
        <WebMethod()>
        Public Shared Function TabUnderwritingRuleSType_Grid3DeleteCommandActionTabUnderwritingRuleSType(TabUnderwritingRuleSTypeUnderwritingRuleStatus1 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                    With New DataManagerFactory("DELETE FROM TabUnderwritingRuleSType WHERE TABUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS = @:UNDERWRITINGRULESTATUS1", "TabUnderwritingRuleSType", "Linked.Underwriting")
                    .AddParameter("UNDERWRITINGRULESTATUS1", DbType.Decimal, 0, False, TabUnderwritingRuleSTypeUnderwritingRuleStatus1)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "TabUnderwritingRuleSType_Grid3DeleteCommandActionTabUnderwritingRuleSType", String.Empty)
            End Try
            
            Return resultData
        End Function

        <WebMethod()>
        Public Shared Function TabUnderwritingRuleSType_Grid2SelectCommandActionTabUnderwritingRuleSType() As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            Dim response As Object = New With {.Result = 0}
            Dim responseList As New List(Of Object)
            
            Try
                InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")

                With New DataManagerFactory("Select MAX(TABUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS) UNDERWRITINGRULESTATUS FROM TABUNDERWRITINGRULESTYPE TABUNDERWRITINGRULESTYPE ", "TabUnderwritingRuleSType", "Linked.Underwriting")

                    response.Result = .QueryExecuteScalarToInteger()
                End With
                With resultData
                    .Count = 1
                    .Data = response
                End With
            
            If responseList.Count <> 0 Then          
		    
            End If
                
            Catch ex As Exception            
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "TabUnderwritingRuleSType_Grid2SelectCommandActionTabUnderwritingRuleSType", String.Empty)
            End Try
            
            Return resultData
        End Function

        <WebMethod()>
        Public Shared Function TabUnderwritingRuleSTypeTranslator_GridTblDataLoad(filter As String) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            Dim response As Object = New With {.UnderwritingRuleStatus = 0, .LanguageId = 0, .Description = String.Empty, .ShortDescription = String.Empty}
            Dim selectDataTableItem As DataTable
            Dim responseList As New List(Of Object)
            
            
            Try
                InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")

                With New DataManagerFactory("SELECT TABUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS, TRANSUNDERWRITINGRULESTYPE.LANGUAGEID, TRANSUNDERWRITINGRULESTYPE.DESCRIPTION, TRANSUNDERWRITINGRULESTYPE.SHORTDESCRIPTION FROM TABUNDERWRITINGRULESTYPE TABUNDERWRITINGRULESTYPE  LEFT JOIN TRANSUNDERWRITINGRULESTYPE TRANSUNDERWRITINGRULESTYPE ON TRANSUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS = TABUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS ", "TabUnderwritingRuleSType", "Linked.Underwriting")

                    selectDataTableItem = .QueryExecuteToTable(True)
                End With
                With selectDataTableItem
                    If Not IsNothing(.Rows) AndAlso .Rows.Count > 0 Then
                        For Each itemData As DataRow In .Rows
                            response = New With {.UnderwritingRuleStatus = itemData.NumericValue("UNDERWRITINGRULESTATUS"), .LanguageId = itemData.NumericValue("LANGUAGEID"), .Description = itemData.StringValue("DESCRIPTION"), .ShortDescription = itemData.StringValue("SHORTDESCRIPTION")}
                            
                            responseList.Add(response)
                        Next

                        With resultData
                            .Count = responseList.Count
                            .Data = responseList
                        End With
                    End If
                End With
            
            If responseList.Count <> 0 Then          
		    
            End If
                
            Catch ex As Exception            
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "TabUnderwritingRuleSTypeTranslator_GridTblDataLoad", String.Empty)
            End Try
            
            Return resultData
        End Function

        <WebMethod()>
        Public Shared Function TabUnderwritingRuleSTypeTranslator_Grid1UpdateCommandActionTransUnderwritingRuleSType(DESCRIPTION1 As String, SHORTDESCRIPTION2 As String, UPDATEUSERCODE2 As Decimal, TransUnderwritingRuleSTypeUnderwritingRuleStatus4 As Decimal, TransUnderwritingRuleSTypeLanguageId5 As Decimal) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim resultData As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True, .Count = 0}
            
            Try
               InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                With New DataManagerFactory("UPDATE TransUnderwritingRuleSType SET DESCRIPTION = @:DESCRIPTION1, SHORTDESCRIPTION = @:SHORTDESCRIPTION2, UPDATEUSERCODE = @:UPDATEUSERCODE2 WHERE TRANSUNDERWRITINGRULESTYPE.UNDERWRITINGRULESTATUS = @:UNDERWRITINGRULESTATUS4 AND TRANSUNDERWRITINGRULESTYPE.LANGUAGEID = @:LANGUAGEID5", "TransUnderwritingRuleSType", "Linked.Underwriting")
                    .AddParameter("DESCRIPTION1", DbType.AnsiString, 0, (DESCRIPTION1 = String.Empty), DESCRIPTION1)
                    .AddParameter("SHORTDESCRIPTION2", DbType.AnsiString, 0, (SHORTDESCRIPTION2 = String.Empty), SHORTDESCRIPTION2)
                    .AddParameter("UPDATEUSERCODE2", DbType.Decimal, 0, False, UPDATEUSERCODE2)
                    .AddParameter("UNDERWRITINGRULESTATUS4", DbType.Decimal, 0, False, TransUnderwritingRuleSTypeUnderwritingRuleStatus4)
                    .AddParameter("LANGUAGEID5", DbType.Decimal, 0, False, TransUnderwritingRuleSTypeLanguageId5)
 
                    .CommandExecute()
              End With

            Catch ex As Exception
                resultData = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "TabUnderwritingRuleSTypeTranslator_Grid1UpdateCommandActionTransUnderwritingRuleSType", String.Empty)
            End Try
            
            Return resultData
        End Function


#End Region

#Region "Lookups Web Methods"


        <WebMethod(EnableSession:=True)>
        Public Shared Function LookUpForRecordStatus(id As String) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim result As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True}
            Dim resultData As DataTable = Nothing
            Dim newLookupList As New List(Of InMotionGIT.Common.DataType.LookUpValue)                       
            
            Try
                InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                 
                Dim UserInfo As New InMotionGIT.Membership.Providers.MemberContext
                With New DataManagerFactory(String.Format(CultureInfo.CurrentCulture,
                                                          "SELECT  TRIM(ETRANRECORDSTATUS.RECORDSTATUS) RECORDSTATUS, ETRANRECORDSTATUS.DESCRIPTION FROM ETRANRECORDSTATUS ETRANRECORDSTATUS  WHERE ETRANRECORDSTATUS.LANGUAGEID = {0}  AND NOT ETRANRECORDSTATUS.DESCRIPTION IS NULL ORDER BY DESCRIPTION", InMotionGIT.FASI.Support.Handlers.LanguageHandler.ContextLanguageId()), 
                                            "ETranRecordStatus", "Linked.Common")

                    
                    resultData = .QueryExecuteToTable(True)
                End With

                If Not IsNothing(resultData) Then
                    For Each item As DataRow In resultData.Rows
                        newLookupList.Add(New InMotionGIT.Common.DataType.LookUpValue With {.Code = item.StringValue("RecordStatus"),
                                                                                            .Description = item.StringValue("Description")})
                    Next
                End If

                result.Data = newLookupList

            Catch ex As Exception
                result = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "LookUpForRecordStatus", String.Empty)
            End Try
                        
            Return result
        End Function

        <WebMethod(EnableSession:=True)>
        Public Shared Function LookUpForLanguageIdTranslator(id As String) As InMotionGIT.FrontOffice.Support.DataType.ClientActionResult
            
            Dim result As New InMotionGIT.FrontOffice.Support.DataType.ClientActionResult With {.Success = True}
            Dim resultData As DataTable = Nothing
            Dim newLookupList As New List(Of InMotionGIT.Common.DataType.LookUpValue)                       
            
            Try
                InMotionGIT.FASI.Support.Authentication.AuthorizationProcess("EASE1,Suscriptor")
                 
                Dim UserInfo As New InMotionGIT.Membership.Providers.MemberContext
                With New DataManagerFactory(String.Format(CultureInfo.CurrentCulture,
                                                          "SELECT TRANSLANGUAGE.LANGUAGECODEID, TRANSLANGUAGE.DESCRIPTION FROM TRANSLANGUAGE TRANSLANGUAGE WHERE TRANSLANGUAGE.LANGUAGEID = {0} AND NOT TRANSLANGUAGE.DESCRIPTION IS NULL ORDER BY DESCRIPTION", InMotionGIT.FASI.Support.Handlers.LanguageHandler.ContextLanguageId()), 
                                            "TransLanguage", "Linked.Common")

                    
                    resultData = .QueryExecuteToTable(True)
                End With

                If Not IsNothing(resultData) Then
                    For Each item As DataRow In resultData.Rows
                        newLookupList.Add(New InMotionGIT.Common.DataType.LookUpValue With {.Code = item.NumericValue("LanguageCodeID"),
                                                                                            .Description = item.StringValue("Description")})
                    Next
                End If

                result.Data = newLookupList

            Catch ex As Exception
                result = InMotionGIT.FrontOffice.Support.ExceptionHandler.ProcessClientAction(ex, "H5MantEstadoReglasSuscripcion", "LookUpForLanguageIdTranslator", String.Empty)
            End Try
                        
            Return result
        End Function

#End Region

#Region "Form Actions"


#End Region





#Region "Common Utilities"

        Private Shared Sub SetDefaultValuesFromQueryString(formData As EntryData)

        End Sub	


#End Region

#Region "Form Contracts"

        <Serializable()>
        <DataContract()>
        Public Class EntryData

            <DataMember()> Public Property InstanceFormId As String
            <DataMember()> Public Property TabUnderwritingRuleSTypeCollectionUnderwritingRuleStatus As System.Double
            <DataMember()> Public Property TabUnderwritingRuleSTypeCollectionCreatorUserCode As System.Double
            <DataMember()> Public Property TabUnderwritingRuleSTypeCollectionCreationDate As System.DateTime
            <DataMember()> Public Property TabUnderwritingRuleSTypeCollectionUpdateUserCode As System.Double
            <DataMember()> Public Property TabUnderwritingRuleSTypeCollectionUpdateDate As System.DateTime
            <DataMember()> Public Property TabUnderwritingRuleSTypeCollectionDescription As System.String
            <DataMember()> Public Property TabUnderwritingRuleSTypeCollectionShortDescription As System.String
            <DataMember()> Public Property TabUnderwritingRuleSTypeCollectionRecordStatus As System.Double
            <DataMember()> Public Property TabUnderwritingRuleSType_Grid_TabUnderwritingRuleSType_Item As List(Of TabUnderwritingRuleSType_Grid_TabUnderwritingRuleSType_ItemItem)
            <DataMember()> Public Property TabUnderwritingRuleSTypeCollectionLanguageId As System.Double
            <DataMember()> Public Property TabUnderwritingRuleSTypeTranslator_Grid_TabUnderwritingRuleSType_Item As List(Of TabUnderwritingRuleSTypeTranslator_Grid_TabUnderwritingRuleSType_ItemItem)

        End Class

        <Serializable()>
        <DataContract()>
        Public Class TabUnderwritingRuleSType_Grid_TabUnderwritingRuleSType_ItemItem

            <DataMember()> Public Property UnderwritingRuleStatus As System.Double
            <DataMember()> Public Property CreatorUserCode As System.Double
            <DataMember()> Public Property CreationDate As System.DateTime
            <DataMember()> Public Property UpdateUserCode As System.Double
            <DataMember()> Public Property UpdateDate As System.DateTime
            <DataMember()> Public Property Description As System.String
            <DataMember()> Public Property ShortDescription As System.String
            <DataMember()> Public Property RecordStatus As System.Double

        End Class

        <Serializable()>
        <DataContract()>
        Public Class TabUnderwritingRuleSTypeTranslator_Grid_TabUnderwritingRuleSType_ItemItem

            <DataMember()> Public Property UnderwritingRuleStatus As System.Double
            <DataMember()> Public Property LanguageId As System.Double
            <DataMember()> Public Property Description As System.String
            <DataMember()> Public Property ShortDescription As System.String

        End Class


#End Region

    End Class

End Namespace

