<%@ Page Language="VB" MasterPageFile="~/fasi/FASI.master" AutoEventWireup="false" %>
<%@ MasterType TypeName="FASI" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <!-- This code was generated by Form Designer v7.3.34.1 at 2020-01-17 10:09:53 a. m. model release 1, Form Generator v1.0.37.30 -->
    <!-- Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. -->
    
    <!-- Bootstrap -->
    <link rel='stylesheet' href='/fasi/assets/css/bootstrap-datetimepicker.min.css' />
    <link rel='stylesheet' href='/fasi/assets/css/bootstrap-table.min.css' />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
   <![endif]-->
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceholder1" runat="Server">
    <div class="ibox">
     <div class="ibox-content">
        <form id="HT5CancerQuestionnaireUWMainForm">
            <input type="hidden" id="HT5CancerQuestionnaireUWFormId" name="HT5CancerQuestionnaireUWFormId" value="" />
            <div id="alerts-container"></div>
			<div class="row">
            <!-- Container content -->
                        <!-- Container: part0ca zone -->
                        <div  class='col-md-12'>

                  <div id="part0ca" class='panel panel-default' disabled>
                    <div class='panel-heading' title=''></div>
                 <div class="panel-body">
    <!-- Container content -->
                <!-- image0 Image -->
                <div class='col-md-2 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-8'>
                                     <img src='/images/Banners/Life Insurance/3.jpg' id='image0' class='img-responsive ' alt='' width='40'  title='image 0'/>

                    </div>
                  </div>
                </div>
                <!-- ClientName text -->
                <div class='col-md-6 form-horizontal col-md-offset-6'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='ClientNameLabel' class='control-label' for='ClientName'>Solicitante del seguro</label>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='ClientName' name='ClientName' title='Solicitante del seguro' type='text' disabled='disabled' size='30' maxlength='30'/>
                    </div>
                  </div>
                </div>
                <!-- uwcaseid text -->
                <div class='col-md-4 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='uwcaseidLabel' class='control-label' for='uwcaseid'>Solicitud</label>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='uwcaseid' name='uwcaseid' title='' type='text' disabled='disabled' size='15' maxlength='15'/>
                    </div>
                  </div>
                </div>
    <!-- End Container content -->
                 </div>
               </div>
                        </div>
                        <!-- End Container: part0ca zone -->
                        <!-- Container: part1ca zone -->
                        <div  class='col-md-12'>

                  <div id="part1ca" class='panel panel-default'>
                    <div class='panel-heading' title=''>El siguiente cuestionario debe ser completado por el solicitante del seguro. Por favor conteste todas las preguntas.</div>
                 <div class="panel-body">
    <!-- Container content -->
                <!-- TypeOfCancer dropdownlist -->
                        <div class='col-md-12 margin-top-1'></div>
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='TypeOfCancerLabel' class='control-label' style='font-weight: bold;' for='TypeOfCancer'>1. Tipo de cáncer o tumor</label><span id='TypeOfCancerRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <select id='TypeOfCancer' name='TypeOfCancer' class='form-control' title='Tipo de cáncer'>
                                    <option value='1'>Cancer</option>
                                    <option value='2'>Tumor</option>
                                    <option value='3'>Quistes</option>
                                </select>

                    </div>
                  </div>
                </div>
                <!-- DateDiagnosed datepicker -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='DateDiagnosedLabel' class='control-label' style='font-weight: bold;' for='DateDiagnosed'>2. Fecha del diagnóstico</label><span id='DateDiagnosedRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <div class='input-group date' id='DateDiagnosed_group'>
                                    <input id='DateDiagnosed' name='DateDiagnosed' type='text' class='form-control' title='' size='10' maxlength='10'/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                    </div>
                  </div>
                </div>
                <!-- StageOfCancer dropdownlist -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='StageOfCancerLabel' class='control-label' style='font-weight: bold;' for='StageOfCancer'>3. Estado del cáncer</label><span id='StageOfCancerRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <select id='StageOfCancer' name='StageOfCancer' class='form-control' title='Indica el estado del cáncer'>
                                    <option value='0'>1</option>
                                    <option value='1'>2</option>
                                    <option value='2'>2a</option>
                                    <option value='3'>2b</option>
                                    <option value='4'>2c</option>
                                    <option value='5'>3</option>
                                    <option value='6'>3a</option>
                                    <option value='7'>3b</option>
                                    <option value='8'>4</option>
                                </select>

                    </div>
                  </div>
                </div>
                <!-- ScaleColonRectalCancer dropdownlist -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='ScaleColonRectalCancerLabel' class='control-label' for='ScaleColonRectalCancer'>Si el cáncer es de colon o rectal: Escala Dukes</label>
                    </div>
                    <div class='col-md-8'>
                        <select id='ScaleColonRectalCancer' name='ScaleColonRectalCancer' class='form-control' title='Si el cáncer es de colon o rectal indique la Escala Dukes'>
                                    <option value='0'>A</option>
                                    <option value='1'>B1</option>
                                    <option value='2'>B2-3</option>
                                    <option value='3'>C1</option>
                                    <option value='4'>C2</option>
                                    <option value='5'>D</option>
                                </select>

                    </div>
                  </div>
                </div>
                <!-- LevelMelanoma dropdownlist -->
                <div class='col-md-6 form-horizontal col-md-offset-6'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='LevelMelanomaLabel' class='control-label' for='LevelMelanoma'>Si es un melanoma: Nivel Clark</label>
                    </div>
                    <div class='col-md-8'>
                        <select id='LevelMelanoma' name='LevelMelanoma' class='form-control' title='Nivel Clark'>
                                    <option value='0'>I</option>
                                    <option value='1'>II</option>
                                    <option value='2'>III</option>
                                    <option value='3'>IV</option>
                                    <option value='4'>V</option>
                                </select>

                    </div>
                  </div>
                </div>
                <!-- GradeProstateCancer dropdownlist -->
                <div class='col-md-6 form-horizontal col-md-offset-6'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='GradeProstateCancerLabel' class='control-label' for='GradeProstateCancer'>Si es un cáncer de próstata: Grado Gleason</label>
                    </div>
                    <div class='col-md-8'>
                        <select id='GradeProstateCancer' name='GradeProstateCancer' class='form-control' title='If is a prostate cancer, indicate de gleasons grade'>
                                    <option value='0'>2-5</option>
                                    <option value='1'>6</option>
                                    <option value='2'>7</option>
                                    <option value='3'>8-10</option>
                                </select>

                    </div>
                  </div>
                </div>
                <!-- EvidenceOfRecurringCancer radiobuttonlist -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='EvidenceOfRecurringCancerLabel' class='control-label' style='font-weight: bold;' for='EvidenceOfRecurringCancer'>4. ¿Ha habido alguna evidencia de cáncer recurrente?</label><span id='EvidenceOfRecurringCancerRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                                <div id='EvidenceOfRecurringCancerWrap'>
                <label class='radio-inline'>
                  <input type='radio' name='EvidenceOfRecurringCancer' id='EvidenceOfRecurringCancer_true' value='true' title='Indique si tiene alguna evidencia de cáncer recurrente'/>
                  <span >Si</span>
                </label>
                <label class='radio-inline'>
                  <input type='radio' name='EvidenceOfRecurringCancer' id='EvidenceOfRecurringCancer_false' value='false'/>
                  <span >No</span>
                </label>
                <div id='EvidenceOfRecurringCancer_validate'></div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- DateEvidence datepicker -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='DateEvidenceLabel' class='control-label' for='DateEvidence'>Si la respuesta es Si, indique la fecha</label><span id='DateEvidenceRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <div class='input-group date' id='DateEvidence_group'>
                                    <input id='DateEvidence' name='DateEvidence' type='text' class='form-control' title='' size='10' maxlength='10' disabled/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                    </div>
                  </div>
                </div>
                <!-- LocationRecurringCancer text -->
                <div class='col-md-6 form-horizontal col-md-offset-6'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='LocationRecurringCancerLabel' class='control-label' for='LocationRecurringCancer'>Lozalización</label><span id='LocationRecurringCancerRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='LocationRecurringCancer' name='LocationRecurringCancer' title='Localización del cáncer' type='text' disabled='disabled' size='15' maxlength='15'/>
                    </div>
                  </div>
                </div>
                <!-- DateInitiallyTreated datepicker -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='DateInitiallyTreatedLabel' class='control-label' style='font-weight: bold;' for='DateInitiallyTreated'>5. Fecha inicialmente tratada</label><span id='DateInitiallyTreatedRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <div class='input-group date' id='DateInitiallyTreated_group'>
                                    <input id='DateInitiallyTreated' name='DateInitiallyTreated' type='text' class='form-control' title='' size='10' maxlength='10'/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                    </div>
                  </div>
                </div>
                <!-- DateLastTreated datepicker -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='DateLastTreatedLabel' class='control-label' style='font-weight: bold;' for='DateLastTreated'>6. Fecha del último tratamiento</label><span id='DateLastTreatedRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <div class='input-group date' id='DateLastTreated_group'>
                                    <input id='DateLastTreated' name='DateLastTreated' type='text' class='form-control' title='' size='10' maxlength='10'/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                    </div>
                  </div>
                </div>
                <!-- DateLastSeenByDoctor datepicker -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='DateLastSeenByDoctorLabel' class='control-label' style='font-weight: bold;' for='DateLastSeenByDoctor'>7. Fecha de última visita al doctor</label><span id='DateLastSeenByDoctorRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <div class='input-group date' id='DateLastSeenByDoctor_group'>
                                    <input id='DateLastSeenByDoctor' name='DateLastSeenByDoctor' type='text' class='form-control' title='' size='10' maxlength='10'/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                    </div>
                  </div>
                </div>
                <!-- GrowthMayBeMalignant radiobuttonlist -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='GrowthMayBeMalignantLabel' class='control-label' style='font-weight: bold;' for='GrowthMayBeMalignant'>8. ¿Ha habido alguna evidencia o indicio de que el crecimiento puede ser maligno?</label><span id='GrowthMayBeMalignantRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                                <div id='GrowthMayBeMalignantWrap'>
                <label class='radio-inline'>
                  <input type='radio' name='GrowthMayBeMalignant' id='GrowthMayBeMalignant_true' value='true' title=''/>
                  <span >Si</span>
                </label>
                <label class='radio-inline'>
                  <input type='radio' name='GrowthMayBeMalignant' id='GrowthMayBeMalignant_false' value='false'/>
                  <span >No</span>
                </label>
                <div id='GrowthMayBeMalignant_validate'></div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- DetailsEvidence text -->
                <div class='col-md-6 form-vertical'>
                  <div class='form-group'>
                    <label id='DetailsEvidenceLabel' class='control-label' for='DetailsEvidence'>En caso afirmativo, indique los detalles completos, incluyendo el informe histológico (si lo tiene su médico de cabecera):</label><span id='DetailsEvidenceRequired' class='required-mark'>*</span>
                        <input class='form-control' id='DetailsEvidence' name='DetailsEvidence' title='Detalles completos, incluyendo histología informe del crecimiento' type='text' disabled='disabled' size='35' maxlength='35'/>
                  </div>
                </div>
                <!-- RemovedGrowth radiobuttonlist -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='RemovedGrowthLabel' class='control-label' style='font-weight: bold;' for='RemovedGrowth'>9. ¿El crecimiento ha sido eliminado?</label><span id='RemovedGrowthRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                                <div id='RemovedGrowthWrap'>
                <label class='radio-inline'>
                  <input type='radio' name='RemovedGrowth' id='RemovedGrowth_true' value='true' title=''/>
                  <span >Si</span>
                </label>
                <label class='radio-inline'>
                  <input type='radio' name='RemovedGrowth' id='RemovedGrowth_false' value='false'/>
                  <span >No</span>
                </label>
                <div id='RemovedGrowth_validate'></div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- DetailsInvestigations text -->
                <div class='col-md-6 form-vertical'>
                  <div class='form-group'>
                    <label id='DetailsInvestigationsLabel' class='control-label' for='DetailsInvestigations'>Si no, por favor proporcione detalles de las investigaciones que se han llevado a cabo (como biopsia). Por favor, incluya la fecha(s)</label><span id='DetailsInvestigationsRequired' class='required-mark'>*</span>
                        <input class='form-control' id='DetailsInvestigations' name='DetailsInvestigations' title='Proporcione detalles de las investigaciones cuando el crecimiento no se ha eliminado' type='text' size='35' maxlength='35'/>
                  </div>
                </div>
                <!-- Container: zone0 zone -->
                <div  class='col-md-6'>

                  <div id="zone0">
    <!-- Container content -->
                <!-- labelca label -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group text-left'>
                                  <label id='labelca' title='' style='font-weight: bold;'>10. ¿Qué tratamiento ha tenido para después de la eliminación?</label>

                  </div>
                </div>
                <!-- ChemotherapyTreatmentFollowing checkbox -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='ChemotherapyTreatmentFollowingWrap'>
    <div class='checkbox'>
                                    <label id='ChemotherapyTreatmentFollowingLabel'>
                                        <input id='ChemotherapyTreatmentFollowing' name='ChemotherapyTreatmentFollowing' type='checkbox' title='Tratamiento de quimioterapia'  />
                               <span >Quimioterapia</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- RadiotherapyTreatmentFollowing checkbox -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='RadiotherapyTreatmentFollowingWrap'>
    <div class='checkbox'>
                                    <label id='RadiotherapyTreatmentFollowingLabel'>
                                        <input id='RadiotherapyTreatmentFollowing' name='RadiotherapyTreatmentFollowing' type='checkbox' title='Tratamiento de radioterapia'  />
                               <span >Radioterapia</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- MedicationTreatmentFollowing checkbox -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='MedicationTreatmentFollowingWrap'>
    <div class='checkbox'>
                                    <label id='MedicationTreatmentFollowingLabel'>
                                        <input id='MedicationTreatmentFollowing' name='MedicationTreatmentFollowing' type='checkbox' title='Tratamiento médico'  />
                               <span >Medicación</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- OtherTreatmentFollowing text -->
                <div class='col-md-12 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='OtherTreatmentFollowingLabel' class='control-label' for='OtherTreatmentFollowing'>Otro tratamiento</label>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='OtherTreatmentFollowing' name='OtherTreatmentFollowing' title='Tipo de tratamiento después de eliminado el crecimiento.' type='text' size='35' maxlength='35'/>
                    </div>
                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone0 zone -->
                <!-- StillFollowedUp radiobuttonlist -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-6 form-vertical'>
                  <div class='form-group'>
                    <label id='StillFollowedUpLabel' class='control-label' style='font-weight: bold;' for='StillFollowedUp'>11. ¿Sigue siendo objeto de seguimiento del tratamiento después de la eliminación?</label><span id='StillFollowedUpRequired' class='required-mark'>*</span>
                                    <div class='input-group'>
            <div id='StillFollowedUpWrap'>
                <label class='radio-inline'>
                  <input type='radio' name='StillFollowedUp' id='StillFollowedUp_true' value='true' title=''/>
                  <span >Si</span>
                </label>
                <label class='radio-inline'>
                  <input type='radio' name='StillFollowedUp' id='StillFollowedUp_false' value='false'/>
                  <span >No</span>
                </label>
                <div id='StillFollowedUp_validate'></div>
            </div>
                </div>

                  </div>
                </div>
                <!-- HowOften text -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='HowOftenLabel' class='control-label' for='HowOften'>En caso afirmativo, indique con qué frecuencia</label><span id='HowOftenRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='HowOften' name='HowOften' title='Frecuencia de aplicación del tratamiento' type='text' disabled='disabled' size='35' maxlength='35'/>
                    </div>
                  </div>
                </div>
                <!-- DateOfDischargedFollowUp datepicker -->
                <div class='col-md-6 form-horizontal col-md-offset-6'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='DateOfDischargedFollowUpLabel' class='control-label' for='DateOfDischargedFollowUp'>Si no, cuando le dieron de alta en el seguimiento?</label><span id='DateOfDischargedFollowUpRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <div class='input-group date' id='DateOfDischargedFollowUp_group'>
                                    <input id='DateOfDischargedFollowUp' name='DateOfDischargedFollowUp' type='text' class='form-control' title='' size='10' maxlength='10'/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                    </div>
                  </div>
                </div>
                <!-- Container: zone1 zone -->
                <div  class='col-md-6'>

                  <div id="zone1">
    <!-- Container content -->
                <!-- label2ca label -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group text-left'>
                                  <label id='label2ca' title='' style='font-weight: bold;'>12. Por favor, proporcione información detallada de todos los tratamientos que ha recibido en el pasado</label>

                  </div>
                </div>
                <!-- SurgeryTreatment checkbox -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='SurgeryTreatmentWrap'>
    <div class='checkbox'>
                                    <label id='SurgeryTreatmentLabel'>
                                        <input id='SurgeryTreatment' name='SurgeryTreatment' type='checkbox' title=''  />
                               <span >Cirugía</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- DateSurgeryTreatment datepicker -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='DateSurgeryTreatmentLabel' class='control-label' for='DateSurgeryTreatment'>Fecha</label><span id='DateSurgeryTreatmentRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <div class='input-group date' id='DateSurgeryTreatment_group'>
                                    <input id='DateSurgeryTreatment' name='DateSurgeryTreatment' type='text' class='form-control' title='' size='10' maxlength='10' disabled/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                    </div>
                  </div>
                </div>
                <!-- ChemotherapyTreatment checkbox -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='ChemotherapyTreatmentWrap'>
    <div class='checkbox'>
                                    <label id='ChemotherapyTreatmentLabel'>
                                        <input id='ChemotherapyTreatment' name='ChemotherapyTreatment' type='checkbox' title=''  />
                               <span >Quimioterapia</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- DateChemotherapyTreatment datepicker -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='DateChemotherapyTreatmentLabel' class='control-label' for='DateChemotherapyTreatment'>Fecha</label><span id='DateChemotherapyTreatmentRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <div class='input-group date' id='DateChemotherapyTreatment_group'>
                                    <input id='DateChemotherapyTreatment' name='DateChemotherapyTreatment' type='text' class='form-control' title='' size='10' maxlength='10' disabled/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                    </div>
                  </div>
                </div>
                <!-- RadiationTreatment checkbox -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='RadiationTreatmentWrap'>
    <div class='checkbox'>
                                    <label id='RadiationTreatmentLabel'>
                                        <input id='RadiationTreatment' name='RadiationTreatment' type='checkbox' title=''  />
                               <span >Radiación</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- DateRadiationTreatment datepicker -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='DateRadiationTreatmentLabel' class='control-label' for='DateRadiationTreatment'>Fecha</label><span id='DateRadiationTreatmentRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <div class='input-group date' id='DateRadiationTreatment_group'>
                                    <input id='DateRadiationTreatment' name='DateRadiationTreatment' type='text' class='form-control' title='' size='10' maxlength='10' disabled/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                    </div>
                  </div>
                </div>
                <!-- HormoneTreatment checkbox -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='HormoneTreatmentWrap'>
    <div class='checkbox'>
                                    <label id='HormoneTreatmentLabel'>
                                        <input id='HormoneTreatment' name='HormoneTreatment' type='checkbox' title=''  />
                               <span >Hormonas</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- DateHormoneTreatment datepicker -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='DateHormoneTreatmentLabel' class='control-label' for='DateHormoneTreatment'>Fecha</label><span id='DateHormoneTreatmentRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <div class='input-group date' id='DateHormoneTreatment_group'>
                                    <input id='DateHormoneTreatment' name='DateHormoneTreatment' type='text' class='form-control' title='' size='10' maxlength='10' disabled/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                    </div>
                  </div>
                </div>
                <!-- OtherTreatment checkbox -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='OtherTreatmentWrap'>
    <div class='checkbox'>
                                    <label id='OtherTreatmentLabel'>
                                        <input id='OtherTreatment' name='OtherTreatment' type='checkbox' title=''  />
                               <span >Otro tratamiento</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- DateOtherTreatment datepicker -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='DateOtherTreatmentLabel' class='control-label' for='DateOtherTreatment'>Fecha</label><span id='DateOtherTreatmentRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <div class='input-group date' id='DateOtherTreatment_group'>
                                    <input id='DateOtherTreatment' name='DateOtherTreatment' type='text' class='form-control' title='' size='10' maxlength='10' disabled/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                    </div>
                  </div>
                </div>
                <!-- NameTreatment text -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group'>
                    <label id='NameTreatmentLabel' class='control-label' for='NameTreatment'>Por favor, proporcione detalles de otros tratamientos (si no ya se ha mencionado)</label>
                        <input class='form-control' id='NameTreatment' name='NameTreatment' title='Name of the treatment recieved not specify in the list' type='text' size='35' maxlength='35'/>
                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone1 zone -->
                <!-- Prognosis radiobuttonlist -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-6 form-vertical'>
                  <div class='form-group'>
                    <label id='PrognosisLabel' class='control-label' style='font-weight: bold;' for='Prognosis'>13. ¿Le han dado ninguna información sobre el pronóstico?</label>
                                    <div class='input-group'>
            <div id='PrognosisWrap'>
                <label class='radio-inline'>
                  <input type='radio' name='Prognosis' id='Prognosis_true' value='true' title=''/>
                  <span >Si</span>
                </label>
                <label class='radio-inline'>
                  <input type='radio' name='Prognosis' id='Prognosis_false' value='false'/>
                  <span >No</span>
                </label>
                <div id='Prognosis_validate'></div>
            </div>
                </div>

                  </div>
                </div>
                <!-- DetailsPrognosis text -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='DetailsPrognosisLabel' class='control-label' for='DetailsPrognosis'>En caso afirmativo, indique los detalles completos</label><span id='DetailsPrognosisRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='DetailsPrognosis' name='DetailsPrognosis' title='Details of the prognosis' type='text' disabled='disabled' size='35' maxlength='35'/>
                    </div>
                  </div>
                </div>
                <!-- label3ca label -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-6 form-vertical'>
                  <div class='form-group text-left'>
                                  <label id='label3ca' title='' style='font-weight: bold;'>14. Por favor, indique todos los tratamientos que actualmente recibe</label>

                  </div>
                </div>
                <!-- ChemotherapyCurrentlyTreatment checkbox -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='ChemotherapyCurrentlyTreatmentWrap'>
    <div class='checkbox'>
                                    <label id='ChemotherapyCurrentlyTreatmentLabel'>
                                        <input id='ChemotherapyCurrentlyTreatment' name='ChemotherapyCurrentlyTreatment' type='checkbox' title=''  />
                               <span >Quimioterapia</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- RadiationCurrentlyTreatment checkbox -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='RadiationCurrentlyTreatmentWrap'>
    <div class='checkbox'>
                                    <label id='RadiationCurrentlyTreatmentLabel'>
                                        <input id='RadiationCurrentlyTreatment' name='RadiationCurrentlyTreatment' type='checkbox' title=''  />
                               <span >Radiación</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- HormoneCurrentlyTreatment checkbox -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='HormoneCurrentlyTreatmentWrap'>
    <div class='checkbox'>
                                    <label id='HormoneCurrentlyTreatmentLabel'>
                                        <input id='HormoneCurrentlyTreatment' name='HormoneCurrentlyTreatment' type='checkbox' title=''  />
                               <span >Hormonas</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- MedicationCurrentlyTreatment checkbox -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-12'>
                                <div id='MedicationCurrentlyTreatmentWrap'>
    <div class='checkbox'>
                                    <label id='MedicationCurrentlyTreatmentLabel'>
                                        <input id='MedicationCurrentlyTreatment' name='MedicationCurrentlyTreatment' type='checkbox' title=''  />
                               <span >Medicacion</span>
                                    </label>
                                </div>
            </div>

                    </div>
                  </div>
                </div>
                <!-- OtherCurrentlyTreatment text -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='OtherCurrentlyTreatmentLabel' class='control-label' for='OtherCurrentlyTreatment'>Otro</label>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='OtherCurrentlyTreatment' name='OtherCurrentlyTreatment' title='Tipo de tratamiento actual' type='text' size='15' maxlength='15'/>
                    </div>
                  </div>
                </div>
                <!-- DetailsCurrentlyTreatment text -->
                <div class='col-md-6 form-vertical'>
                  <div class='form-group'>
                    <label id='DetailsCurrentlyTreatmentLabel' class='control-label' for='DetailsCurrentlyTreatment'>Por favor proporcione todos los detalles del tratamiento</label>
                        <input class='form-control' id='DetailsCurrentlyTreatment' name='DetailsCurrentlyTreatment' title='Detalles del actual tratamiento' type='text' size='35' maxlength='35'/>
                  </div>
                </div>
                <!-- Container: zone2 zone -->
                <div  class='col-md-6'>

                  <div id="zone2">
    <!-- Container content -->
                <!-- YesRestrictedLifeStyle radiobuttonlist -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-12 form-vertical'>
                  <div class='form-group'>
                    <label id='YesRestrictedLifeStyleLabel' class='control-label' style='font-weight: bold;' for='YesRestrictedLifeStyle'>15. ¿Alguna vez ha tenido ausencias regulares de trabajo, o ha estado ausente del trabajo o restringido en su estilo de vida por más de un mes en el tiempo como resultado de lesión o enfermedad?</label>
                                    <div class='input-group'>
            <div id='YesRestrictedLifeStyleWrap'>
                <label class='radio-inline'>
                  <input type='radio' name='YesRestrictedLifeStyle' id='YesRestrictedLifeStyle_true' value='true' title=''/>
                  <span >Si</span>
                </label>
                <label class='radio-inline'>
                  <input type='radio' name='YesRestrictedLifeStyle' id='YesRestrictedLifeStyle_false' value='false'/>
                  <span >No</span>
                </label>
                <div id='YesRestrictedLifeStyle_validate'></div>
            </div>
                </div>

                  </div>
                </div>
                <!-- Container: DetailsAbsensesFromWork grid -->
                <div  class='col-md-12'>

               <div id='DetailsAbsensesFromWorkContainer'>
                    <div id="DetailsAbsensesFromWorktoolbar">
                    <div class='form-inline'>
                        <button id="DetailsAbsensesFromWorkCreateBtn" type="button" class="btn btn-default" data-modal-title="Agregar">
                            Agregar
                        </button>
                        <button id="DetailsAbsensesFromWorkRemoveBtn"  type="button" class="btn btn-danger" disabled data-title="Eliminar">
                            <i class="glyphicon glyphicon-remove"></i>Eliminar
                        </button>
                    </div>
                    </div>
                    <div id='DetailsAbsensesFromWorkTblPlaceHolder'></div>
               </div>

                </div>
                <!-- End Container: DetailsAbsensesFromWork grid -->
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone2 zone -->
                <!-- label3 label -->
                <div class='col-md-6 form-vertical'>
                  <div class='form-group text-left'>
                                  <label id='label3' title='label3' style='font-weight: bold;'>16. Por favor, proporcione el nombre completo y dirección de todos los médicos generales y especialistas que le han tratado o le atiende actualmente para esta enfermedad y otras condiciones.</label>

                  </div>
                </div>
                <!-- Container: DetailsOfMedicalPractitioners grid -->
                <div  class='col-md-6'>

               <div id='DetailsOfMedicalPractitionersContainer'>
                    <div id="DetailsOfMedicalPractitionerstoolbar">
                    <div class='form-inline'>
                        <button id="DetailsOfMedicalPractitionersCreateBtn" type="button" class="btn btn-default" data-modal-title="Agregar">
                            Agregar
                        </button>
                        <button id="DetailsOfMedicalPractitionersRemoveBtn"  type="button" class="btn btn-danger" disabled data-title="Eliminar">
                            <i class="glyphicon glyphicon-remove"></i>Eliminar
                        </button>
                    </div>
                    </div>
                    <div id='DetailsOfMedicalPractitionersTblPlaceHolder'></div>
               </div>

                </div>
                <!-- End Container: DetailsOfMedicalPractitioners grid -->
                <!-- AdditionalInformation Notes -->
                        <div class='col-md-12 margin-top-2'></div>
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='AdditionalInformationLabel' class='control-label' style='font-weight: bold;' for='AdditionalInformation'>17. Información adicional</label>
                    </div>
                    <div class='col-md-8'>
                        <textarea class='form-control' id='AdditionalInformation' name='AdditionalInformation' rows='2' title='Información adicional para el cuestionario'></textarea>

                    </div>
                  </div>
                </div>
    <!-- End Container content -->
                 </div>
               </div>
                        </div>
                        <!-- End Container: part1ca zone -->
                        <!-- Container: Zonadca zone -->
                        <div  class='col-md-12'>

                  <div id="Zonadca" class='panel panel-default'>
                    <div class='panel-heading' title=''></div>
                 <div class="panel-body">
    <!-- Container content -->
                <!-- Container: declaracionca zone -->
                <div  class='col-md-12'>

                  <div id="declaracionca">
    <!-- Container content -->
                <!-- label5ca label -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group text-left'>
                                  <label id='label5ca' title=''>Declaro que las respuestas que he dado son de lo mejor de mi conocimiento,  verdadera y completa,  que no he ocultado ninguna información material que pueda influir en la evaluación o la aceptación de mi solicitud. Reconozco que este cuestionario es parte de la solicitud de seguro de vida y que no revelar algún hecho material conocido para mí, puede invalidar el contrato.</label>

                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: declaracionca zone -->
                <!-- Container: Firmaca zone -->
                <div  class='col-md-12'>

                  <div id="Firmaca">
    <!-- Container content -->
                <!-- DateReceived datepicker -->
                <div class='col-md-4 form-vertical'>
                  <div class='form-group'>
                    <label id='DateReceivedLabel' class='control-label' for='DateReceived'>Fecha</label>
                        <div class='input-group date' id='DateReceived_group'>
                                    <input id='DateReceived' name='DateReceived' type='text' class='form-control' title='Fecha en la que se rellena el cuestionario' size='10' maxlength='10'/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                  </div>
                </div>
                <!-- save button -->
                <div class='col-md-4 form-vertical'>
                  <div class='form-group'>
                    <button id='save' class='ladda-button btn pull-right btn-default' data-style='expand-right' title='Se guarda la información del cuestionario sin procesarlo, a la espera de completar su contenido por parte del solicitante.' >
   <img src='/images/Library/16x16_ASPNetIcons/file_manager_16x16.gif' id='saveImage' />   <span class='ladda-label'>Guardar temporalmente</span><span class='ladda-spinner'></span></button>

                  </div>
                </div>
                <!-- submit button -->
                <div class='col-md-4 form-vertical'>
                  <div class='form-group'>
                    <button id='submit' class='ladda-button btn pull-right btn-default' data-style='expand-right' title='Registra la información del cuestionario y actualiza los requisitos relacionados a la solciitud.' >
   <img src='/images/Library/16x16_ASPNetIcons/mail2_(add)_16x16.gif' id='submitImage' />   <span class='ladda-label'>Enviar</span><span class='ladda-spinner'></span></button>

                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: Firmaca zone -->
    <!-- End Container content -->
                 </div>
               </div>
                        </div>
                        <!-- End Container: Zonadca zone -->
            <!-- End Container content -->

            </div>
        </form>



        <div id='DetailsAbsensesFromWorkPopup' class='modal fade' tabindex='-1' role='dialog' aria-labelledby='edit' aria-hidden='true'>
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title"><span>Información</span></h4>
                    </div>
                    <div class="modal-body">
                      <div class="row">
                        <form id='DetailsAbsensesFromWorkEditForm'>
                            <!-- Container content -->
                                        <!-- DateFrom datepicker -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='DateFromLabel' class='control-label' for='DateFrom'>Desde</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <div class='input-group date' id='DateFrom_group'>
                                                    <input id='DateFrom' name='DateFrom' type='text' class='form-control' title='' size='10' maxlength='10'/>
                                                    <span class='input-group-addon'>
                                                        <span class='glyphicon glyphicon-calendar'></span>
                                                    </span>
                                                </div>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- DateTo datepicker -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='DateToLabel' class='control-label' for='DateTo'>Hasta</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <div class='input-group date' id='DateTo_group'>
                                                    <input id='DateTo' name='DateTo' type='text' class='form-control' title='' size='10' maxlength='10'/>
                                                    <span class='input-group-addon'>
                                                        <span class='glyphicon glyphicon-calendar'></span>
                                                    </span>
                                                </div>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- Details text -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='DetailsLabel' class='control-label' for='Details'>Detalles</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='Details' name='Details' title='' type='text' size='25' maxlength='25'/>
                                            </div>
                                          </div>
                                        </div>
                            <!-- End Container content -->

                        </form>
                      </div>
                    </div>
                    <div class="modal-footer">
                        <button id="DetailsAbsensesFromWorkSaveBtn"  class="btn btn-warning">Guardar</button>
                        <button class="btn"  data-dismiss="modal" aria-hidden="true">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
        <div id='DetailsOfMedicalPractitionersPopup' class='modal fade' tabindex='-1' role='dialog' aria-labelledby='edit' aria-hidden='true'>
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title"><span>Información</span></h4>
                    </div>
                    <div class="modal-body">
                      <div class="row">
                        <form id='DetailsOfMedicalPractitionersEditForm'>
                            <!-- Container content -->
                                        <!-- PractitionerName text -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='PractitionerNameLabel' class='control-label' for='PractitionerName'>Nombre</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='PractitionerName' name='PractitionerName' title='' type='text' size='30' maxlength='30'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- PhonePractitioner text -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='PhonePractitionerLabel' class='control-label' for='PhonePractitioner'>Teléfono</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='PhonePractitioner' name='PhonePractitioner' title='Teléfono del médico o especialista.' type='text' size='15' maxlength='15'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- eMailPractitioner text -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='eMailPractitionerLabel' class='control-label' for='eMailPractitioner'>Correo</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='eMailPractitioner' name='eMailPractitioner' title='Correo electrónico del médico o especialista.' type='email' size='50' maxlength='50'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- AddresPractitioner text -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='AddresPractitionerLabel' class='control-label' for='AddresPractitioner'>Dirección</label>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='AddresPractitioner' name='AddresPractitioner' title='' type='text' size='45' maxlength='45'/>
                                            </div>
                                          </div>
                                        </div>
                            <!-- End Container content -->

                        </form>
                      </div>
                    </div>
                    <div class="modal-footer">
                        <button id="DetailsOfMedicalPractitionersSaveBtn"  class="btn btn-warning">Guardar</button>
                        <button class="btn"  data-dismiss="modal" aria-hidden="true">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>


    </div>
  </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="footer" runat="Server">
    <script src='/fasi/assets/js/bootstrap-datetimepicker.min.js'></script>
    <script src='/fasi/assets/js/bootstrap-table.min.js'></script>
    <script src='/fasi/assets/js/bootstrap-table-es-CR.min.js'></script>
    <script src='/fasi/app/js/TableHelper.js?rel=20200117100953907'></script>


    <script src="HT5CancerQuestionnaireUW.js?rel=20200117100953907"></script>
 
</asp:Content>