<%@ Page Language="VB" MasterPageFile="~/fasi/FASI.master" AutoEventWireup="false" %>
<%@ MasterType TypeName="FASI" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <!-- This code was generated by Form Designer v7.1.212.1 at 2018/11/07 11:52:47 a.m. model release 2, Form Generator v1.0.33.2 -->
    <!-- Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. -->
    
    <!-- Bootstrap -->
    <link rel='stylesheet' href='/fasi/assets/css/ladda-themeless.min.css' />
    <link rel='stylesheet' href='/fasi/assets/css/bootstrap-datetimepicker.min.css' />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
   <![endif]-->
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceholder1" runat="Server">
    <div class="ibox">
     <div class="ibox-content">
        <form id="HT5NNCotizacionPolizaHogar4PagoMainForm">
            <input type="hidden" id="HT5NNCotizacionPolizaHogar4PagoFormId" name="HT5NNCotizacionPolizaHogar4PagoFormId" value="" />
            <div id="alerts-container"></div>
			<div class="row">
            <!-- Container content -->
                        <!-- Container: zone1 zone -->
                        <div  class='col-md-12'>

                  <div id="zone1" class='panel panel-default'>
                    <div class='panel-heading' title=''></div>
                 <div class="panel-body">
    <!-- Container content -->
                <!-- EffectiveDate datepicker -->
                <div class='col-md-3 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='EffectiveDateLabel' class='control-label' for='EffectiveDate'>Fecha de efecto</label>
                    </div>
                    <div class='col-md-8'>
                        <div class='input-group date' id='EffectiveDate_group'>
                                    <input id='EffectiveDate' name='EffectiveDate' type='text' class='form-control' title='Fecha de efecto (inicio de vigencia) de la póliza o certificado.' size='10' maxlength='10' disabled/>
                                    <span class='input-group-addon'>
                                        <span class='glyphicon glyphicon-calendar'></span>
                                    </span>
                                </div>
                    </div>
                  </div>
                </div>
                <!-- ProductCode dropdownlist -->
                <div class='col-md-3 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='ProductCodeLabel' class='control-label' for='ProductCode'>Plan</label><span id='ProductCodeRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <select id='ProductCode' name='ProductCode' class='form-control' title='Código del producto.' disabled='disabled'>
                                </select>

                    </div>
                  </div>
                </div>
                <!-- uwcaseid text -->
                <div class='col-md-3 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='uwcaseidLabel' class='control-label hidden' for='uwcaseid'>Caso en tratamiento</label>
                    </div>
                    <div class='col-md-8'>
                        <p id='uwcaseid' name='uwcaseid' class='form-control-static@Control.Class@'></p>
                    </div>
                  </div>
                </div>
                <!-- LineOfBusiness dropdownlist -->
                <div class='col-md-3 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='LineOfBusinessLabel' class='control-label hidden' for='LineOfBusiness'>Ramo</label><span id='LineOfBusinessRequired' class='required-mark hidden'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <select id='LineOfBusiness' name='LineOfBusiness' class='form-control hidden' title='Código del ramo comercial.'>
                                </select>

                    </div>
                  </div>
                </div>
    <!-- End Container content -->
                 </div>
               </div>
                        </div>
                        <!-- End Container: zone1 zone -->
                        <!-- Container: zone8 zone -->
                        <div  class='col-md-12'>

                  <div id="zone8">
    <!-- Container content -->
                <!-- Container: zone10 zone -->
                <div  class='col-md-6'>

                  <div id="zone10">
    <!-- Container content -->
                <!-- Container: HT5NNCotizacionPolizaHogarSecuencia SubPage -->
                <div  class='col-md-12'>

    <!-- Container content -->
    <!-- End Container content -->
                </div>
                <!-- End Container: HT5NNCotizacionPolizaHogarSecuencia SubPage -->
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone10 zone -->
                <!-- Container: zone44Pago zone -->
                <div  class='col-md-6'>

                  <div id="zone44Pago" class='panel panel-default'>
                    <div class='panel-heading' title='Datos del pago'></div>
                 <div class="panel-body">
    <!-- Container content -->
                <!-- label0 label -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group text-center'>
                                  <label id='label0' title='Datos del pago' style='font-weight: bold; font-size: 12px;'>DATOS DEL PAGO</label>

                  </div>
                </div>
                <!-- Container: zone22 zone -->
                <div  class='col-md-12'>

                  <div id="zone22">
    <!-- Container content -->
                <!-- Container: zone26 zone -->
                <div  class='col-md-6'>

                  <div id="zone26">
    <!-- Container content -->
                <!-- CreditCardType radiobuttonlist -->
                <div class='col-md-6 form-vertical'>
                  <div class='form-group'>
                    <label id='CreditCardTypeLabel' class='control-label' for='CreditCardType'></label><span id='CreditCardTypeRequired' class='required-mark'>*</span>
                                    <div id='CreditCardType_Dynamic'>
                </div>
                <div id='CreditCardType_validate'></div>

                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone26 zone -->
                <!-- Container: zone27 zone -->
                <div  class='col-md-6'>

                  <div id="zone27">
    <!-- Container content -->
                <!-- BankCode dropdownlist -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='BankCodeLabel' class='control-label' for='BankCode'>Banco</label><span id='BankCodeRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <select id='BankCode' name='BankCode' class='form-control' title='Código del Banco'>
                                </select>

                    </div>
                  </div>
                </div>
                <!-- CreditCardNumber text -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='CreditCardNumberLabel' class='control-label' for='CreditCardNumber'>Tarjeta</label><span id='CreditCardNumberRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='CreditCardNumber' name='CreditCardNumber' title='Tarjeta de Crédito' type='text' size='20' maxlength='20'/>
                    </div>
                  </div>
                </div>
                <!-- LocalMonth numeric -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='LocalMonthLabel' class='control-label' for='LocalMonth'>Vencimiento</label><span id='LocalMonthRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                    <div class='col-xs-12 input-group'>                            <div class='input-group'>
    <input class='form-control' id='LocalMonth' name='LocalMonth' title='Mes de Vencimiento' type='text' style='text-align: right'/>                            <div class='input-group-addon'>/</div>
                            </div>
<span class='input-group-btn'></span>    <input class='form-control' id='Year' name='Year' title='Año de Vencimiento' type='text' style='text-align: right'/></div>
                    </div>
                  </div>
                </div>
                <!-- AuthorizationNumber numeric -->
                <div class='col-md-6 form-horizontal'>
                  <div class='form-group'>
                    <div class='col-md-4 text-left'>
                      <label id='AuthorizationNumberLabel' class='control-label' for='AuthorizationNumber'>Nro.Autorización</label><span id='AuthorizationNumberRequired' class='required-mark'>*</span>
                    </div>
                    <div class='col-md-8'>
                        <input class='form-control' id='AuthorizationNumber' name='AuthorizationNumber' title='Número de Autorización' type='text' style='text-align: right'/>
                    </div>
                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone27 zone -->
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone22 zone -->
                <!-- Container: zone19 zone -->
                <div  class='col-md-12'>

                  <div id="zone19">
    <!-- Container content -->
                <!-- buttonGPago button -->
                <div class='col-md-12 form-vertical'>
                  <div class='form-group'>
                    <button id='buttonGPago' class='ladda-button btn pull-right btn-default' data-style='expand-right' title=''  style='font-weight: bold; font-size: 10px; background-color: #BFBFBF;'><span class='ladda-label'>
Finalizar   <img src='/images/Library/16x16_ASPNetIcons/ok_16x16.gif' id='buttonGPagoImage' /></span><span class='ladda-spinner'></span></button>

                  </div>
                </div>
    <!-- End Container content -->
               </div>
                </div>
                <!-- End Container: zone19 zone -->
    <!-- End Container content -->
                 </div>
               </div>
                </div>
                <!-- End Container: zone44Pago zone -->
    <!-- End Container content -->
               </div>
                        </div>
                        <!-- End Container: zone8 zone -->
            <!-- End Container content -->

            </div>
        </form>





    </div>
  </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="footer" runat="Server">
    <script src='/fasi/assets/js/spin.min.js'></script>
    <script src='/fasi/assets/js/ladda.min.js'></script>
    <script src='/fasi/assets/js/ladda.jquery.min.js'></script>
    <script src='/fasi/assets/js/bootstrap-datetimepicker.min.js'></script>
    <script src='/fasi/assets/js/autoNumeric.min.js'></script>


    <script src="HT5NNCotizacionPolizaHogar4Pago.js?rel=20181107115247728"></script>
 
</asp:Content>