<%@ Page Language="VB" MasterPageFile="~/fasi/FASI.master" AutoEventWireup="false" %>
<%@ MasterType TypeName="FASI" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <!-- This code was generated by Form Designer v7.1.215.1 at 2019-02-04 09:47:56 AM model release 2, Form Generator v1.0.34.9 -->
    <!-- Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. -->
    
    <!-- Bootstrap -->
    <link rel='stylesheet' href='/fasi/assets/css/bootstrap-datetimepicker.min.css' />
    <link rel='stylesheet' href='/fasi/assets/css/bootstrap-table.min.css' />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
   <![endif]-->
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceholder1" runat="Server">
    <div class="ibox">
     <div class="ibox-content">
        <form id="NSF2501AMainForm">
            <input type="hidden" id="NSF2501AFormId" name="NSF2501AFormId" value="" />
            <div id="alerts-container"></div>
			<div class="row">
            <!-- Container content -->
                        <!-- Container: Grupo_Acceso_Grid grid -->
                        <div  class='col-md-12'>

                       <div id='Grupo_Acceso_GridContainer'>
                            <div id="Grupo_Acceso_Gridtoolbar">
                            <div class='form-inline'>
                                <button id="Grupo_Acceso_GridCreateBtn" type="button" class="btn btn-default" data-modal-title="Agregar">
                                    Agregar
                                </button>
                                <button id="Grupo_Acceso_GridRemoveBtn"  type="button" class="btn btn-danger" disabled data-title="Eliminar">
                                    <i class="glyphicon glyphicon-remove"></i>Eliminar
                                </button>
                            </div>
                            </div>
                            <div id='Grupo_Acceso_GridTblPlaceHolder'></div>
                       </div>

                        </div>
                        <!-- End Container: Grupo_Acceso_Grid grid -->
            <!-- End Container content -->

            </div>
        </form>



        <div id='Grupo_Acceso_GridPopup' class='modal fade' tabindex='-1' role='dialog' aria-labelledby='edit' aria-hidden='true'>
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title">title</h4>
                    </div>
                    <div class="modal-body">
                      <div class="row">
                        <form id='Grupo_Acceso_GridEditForm'>
                            <!-- Container content -->
                                        <!-- Id_Grupo_Acceso numeric -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='Id_Grupo_AccesoLabel' class='control-label hidden' for='Id_Grupo_Acceso'>Identificador</label><span id='Id_Grupo_AccesoRequired' class='required-mark hidden'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control hidden' id='Id_Grupo_Acceso' name='Id_Grupo_Acceso' title='Código del grupo de acceso.' type='text' style='text-align: right'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- Descripcion text -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='DescripcionLabel' class='control-label' for='Descripcion'>Descripción</label><span id='DescripcionRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='Descripcion' name='Descripcion' title='Descripción del código.' type='text' size='75' maxlength='75'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- Descripcion_Corta text -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='Descripcion_CortaLabel' class='control-label' for='Descripcion_Corta'>Descripcion corta</label><span id='Descripcion_CortaRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control' id='Descripcion_Corta' name='Descripcion_Corta' title='Descripción abreviada del código.' type='text' size='40' maxlength='40'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- Estado_Registro dropdownlist -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='Estado_RegistroLabel' class='control-label' for='Estado_Registro'>Estado Registro</label><span id='Estado_RegistroRequired' class='required-mark'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <select id='Estado_Registro' name='Estado_Registro' class='form-control' title='Estado del registro.'>
                                                </select>

                                            </div>
                                          </div>
                                        </div>
                                        <!-- CreationDate datepicker -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='CreationDateLabel' class='control-label hidden' for='CreationDate'>Fecha de Creación</label><span id='CreationDateRequired' class='required-mark hidden'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <div class='input-group date hidden' id='CreationDate_group'>
                                                    <input id='CreationDate' name='CreationDate' type='text' class='form-control hidden' title='Fecha del computador en que se crea el registro.' size='19' maxlength='19'/>
                                                    <span class='input-group-addon'>
                                                        <span class='glyphicon glyphicon-calendar'></span>
                                                    </span>
                                                </div>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- CreatorUserCode numeric -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='CreatorUserCodeLabel' class='control-label hidden' for='CreatorUserCode'>User Code Creador</label><span id='CreatorUserCodeRequired' class='required-mark hidden'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control hidden' id='CreatorUserCode' name='CreatorUserCode' title='Código del usuario que crea el registro.' type='text' style='text-align: right'/>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- UpdateDate datepicker -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='UpdateDateLabel' class='control-label hidden' for='UpdateDate'>Fecha de Actualización del Registro</label><span id='UpdateDateRequired' class='required-mark hidden'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <div class='input-group date hidden' id='UpdateDate_group'>
                                                    <input id='UpdateDate' name='UpdateDate' type='text' class='form-control hidden' title='Fecha del computador en que se crea o actualiza el registro.' size='19' maxlength='19'/>
                                                    <span class='input-group-addon'>
                                                        <span class='glyphicon glyphicon-calendar'></span>
                                                    </span>
                                                </div>
                                            </div>
                                          </div>
                                        </div>
                                        <!-- UpdateUserCode numeric -->
                                        <div class='col-md-12 form-horizontal'>
                                          <div class='form-group'>
                                            <div class='col-md-4 text-left'>
                                              <label id='UpdateUserCodeLabel' class='control-label hidden' for='UpdateUserCode'>Código de Usuario Que Actualiza</label><span id='UpdateUserCodeRequired' class='required-mark hidden'>*</span>
                                            </div>
                                            <div class='col-md-8'>
                                                <input class='form-control hidden' id='UpdateUserCode' name='UpdateUserCode' title='Código del usuario que crea o actualiza el registro.' type='text' style='text-align: right'/>
                                            </div>
                                          </div>
                                        </div>
                            <!-- End Container content -->

                        </form>
                      </div>
                    </div>
                    <div class="modal-footer">
                        <button id="Grupo_Acceso_GridSaveBtn"  class="btn btn-warning">Guardar</button>
                        <button class="btn"  data-dismiss="modal" aria-hidden="true">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>


    </div>
  </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="footer" runat="Server">
    <script src='/fasi/assets/js/bootstrap-datetimepicker.min.js'></script>
    <script src='/fasi/assets/js/bootstrap-table.min.js'></script>
    <script src='/fasi/assets/js/bootstrap-table-es-CR.min.js'></script>
    <script src='/fasi/app/js/TableHelper.js?rel=20190204094756045'></script>
    <script src='/fasi/assets/js/bootstrap-table-export.js'></script>
    <script src='/fasi/assets/js/tableExport.min.js'></script>
    <script src='/fasi/assets/js/autoNumeric.min.js'></script>


    <script src="NSF2501A.js?rel=20190204094756045"></script>
 
</asp:Content>